### ISSUE TITLE
web interface: having selected zero VMs will retire all VMs on all coulds !

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#101]
E.g. looking at running VMs on a cloud, ___not___ selecting any VMs and click the retire button will retire ***ALL*** VMs on ***ALL*** clouds !

**Comment by colsond** [comment]
THIS IS "URGENT"

**Comment by rseuster** [comment]
please test

**Comment by rseuster** [comment]
fixed, create new issue when needed
