### ISSUE TITLE
Can't select vm_keyname on Clouds or Defaults even though it exists.

### ISSUE THREAD

**Issue by kcasteels** [hep-gc/cloudscheduler#119]
Error: CV94-1130 cloud update, "dair-ab" failed - specified item does not exist: vm_keyname=common_key-20171006, group_name=testing, cloud_name=dair-ab.

Error: GV07-267 group defaults update specified item does not exist: vm_keyname=common_key-20171006, group_name=testing.

**Comment by crlb** [comment]
both cloud add/update and group defaults fixed on dev.

**Comment by rseuster** [comment]
doesn't show up / works on the web gui

**Comment by kcasteels** [comment]
This is working now. Please double check.

**Comment by rseuster** [comment]
closing
