### ISSUE TITLE
Migrate condor_central_manager field to Defaults on web interface, and add additional field condor_hostname 

### ISSUE THREAD

**Issue by danikam** [hep-gc/cloudscheduler#122]
1. Move condor_central_manager field, which is currently under Groups, to Defaults.

2. Add an additional field underneath the condor_central_manager field in Defaults to specify the name of the condor host (could call it "condor_hostname"). Add a corresponding database entry. If this "condor_hostname" field is not set by the user, it should default to the name of the condor_central_manager.

    Reason: For container work, name of scheduler, DaemonMaster, and Collector is by default the hostname of the container, not the name of the host machine.

**Comment by crlb** [comment]
Two new fields established in the non-super-user controllable csv2_group_defaults: htcondor_fqdn and htcondor_name. cli and groups_view.py upated to manage these new optional values. all htcondor_fqdn set to equal their corresponding condor_central_manager.

csmain csmachines, and csjobs need to updated to use the new values and then we can deprecate condor_central_manager.

**Comment by colsond** [comment]
I still have a couple staging changes in the pollers but i will update to use these new values once ive finalized and committed my current changed.

**Comment by colsond** [comment]
Just to be clear before I implement with the pollers the precedence here is:

For polling data

1. Attempt to query condor via htcondor_name; and if that doesn't work or is Null
2. query via htcondor_fqdn

For containers is each condor daemon in it's own container? The pollers need to query both the schedd and the Collector daemons as well as send direct commands (via htcondor.send_command(), which may need to be changed to work properly in a container format).

**Comment by colsond** [comment]
This should be addressed on dev as of commit c29db2640eee52984dcfb07942b0ae4e49ae2123. The change effects both the machine and job pollers so it would be good to do a test with containers to see if things are acting as expected.

**Comment by crlb** [comment]
Needs testing.

**Comment by danikam** [comment]
Container testing update: csv2 successfully recognizes and reports condor jobs in the queue on the status page with htcondor_fqdn set to "htc-dev.heprc.uvic.ca" (host machine name), and htcondor_name set to "csv2_host" (container hostname) :)

However, csv2 won't launch VMs anymore with the most recent dev (can't get much info from the logs as to why though, so it may be unrelated to these updates).

**Comment by kcasteels** [comment]
This has been changed now.

**Comment by danikam** [comment]
These updates seem to be working well based on recent container testing :) Closing issue.
