### ISSUE TITLE
Cloud update should check that the new attributes as well as authentication settings are valid before changing

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#124]
In glintv2 I made a "validate_repo"  function that was called each time a cloud was added or updated to make sure that the new/updated cloud could make a valid connection to openstack. I think it would be a good idea to do this with csv2 as well.

This thought comes as a result of investigating the authentication errors we saw in the pollers. The CC-west and arbutus have the same users and some people have the credentials saved in their browser. This resulted in the "atlas" user for arbutus being updated with the cc-west password credentials thus causing non stop errors attempting to connect to the cloud.

A validation function would have caught this error at the update step saving a days worth of errors on arbutus.

**Comment by rseuster** [comment]
+1

**Comment by rseuster** [comment]
this can be dangerous if you have connection problems to a cloud.
Still, closing, re-open if you want.
