### ISSUE TITLE
condor queue mixup between csv2 and csv2-dev

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#129]
I am populating the "test" group with jobs on the csv2-dev machine. However, csv2 in the "test" group booted VMs. Jobs show up on csv2-dev as well as on csv2 in the "test" group, but that queue on csv2 is configured to look at a condor queue also on csv2. This queue is empty. How can that be ?

Note, the "testing" group on csv2 is configured to look at a condor queue on csv2-dev.

**Comment by crlb** [comment]
So here is what i think is happening:

    on csv2-dev, you submitted 30 jobs with "Requirements = ( group_name =?= "test" && TARGET.Arch == "x86_64" ) && ( TARGET.OpSys == "LINUX" ) && ( TARGET.Disk >= RequestDisk ) && ( TARGET.Memory >= RequestMemory ) && ( TARGET.HasFileTransfer )" - note the group name.
    on csv2, group test points to csv2.heprc.uvic.ca, but group testing points to csv2-dev.heprc.uvic.ca
    csjobs poller on csv2 is reading the job queue for group testing and adding the jobs to the db unde the group from the requirements expression. I think we need to fix the poller to check the requirements against the current group, and if mismatch/hold the job with reason and not add them to the db.

**Comment by crlb** [comment]
The following is a more complete description of the current issue:

- Multiple HTCondor instances, each with a combination of multiple csv2 and non-csv2 job submitters.

- Considering the job queue on just one of these HTCondor instances, we need select only those jobs that have a requirement group that matches a csv2 group that is pointing to that HTcondor instance, AND that the job owner is associated with that csv2 group. All jobs not meeting these requirement must be ignored.

To Facilitate these requirements, the following changes will be made:

1.  htcondor_supplementary_submitters containing a list of additional job submitters will be to csv2_group_defaults. This list will be used to augment the list of group members who are allowed to submit jobs to this group.
2. csjobs will be modified to retrieve both the list of groups and the list of job submitters for each group prior to scanning the jobs for an HTCondor instance. Any job not matching the group/submitter constraints will be ignored.

**Comment by colsond** [comment]
These restraints should be in place on dev as of commit 1c7b72d5e48060d680a1065718d770e229f0ae24

**Comment by crlb** [comment]
Needs testing.

**Comment by rseuster** [comment]
fixed
