### ISSUE TITLE
cloudscheduler ignores instance flavour setting in the Clouds menu

### ISSUE THREAD

**Issue by danikam** [hep-gc/cloudscheduler#139]
This is a new bug, seen in commit 03414495e96f4b2c994e85370f22191f76ead4bb from Jan. 4. The VM started by cloudscheduler will ignore the flavour setting in Clouds/Settings/VM Flavor (also set in Defaults/VM Flavor), and start the VM with flavour admin_testing_only. See attached screenshots.

A workaround is to explicitly set the desired VM flavour for the target cloud in the job submission file.

![screen shot 2019-01-09 at 11 36 56 am](https://user-images.githubusercontent.com/43050968/50924095-71e80800-1403-11e9-9020-8ba4c2fec4b9.png)
![screen shot 2019-01-09 at 11 37 10 am](https://user-images.githubusercontent.com/43050968/50924100-76142580-1403-11e9-8960-f090136382c7.png)
<img width="1279" alt="screen shot 2019-01-09 at 11 40 11 am" src="https://user-images.githubusercontent.com/43050968/50924113-7c0a0680-1403-11e9-8a4e-0fa90e7de095.png">

**Comment by mhpx** [comment]
the scheduler boots the flavor that view_idle_jobs has selected based on requirements defaults etc. So if the admin_testing_flavor is overriding things it should not this will need to be resolved in the view.

**Comment by crlb** [comment]
fix  c2c46552158604d03756646be9d722a04f197d2c view_groups_of_idle_jobs modified to respect default flavor.
