### ISSUE TITLE
have a --force-overwrite option to metadata-load

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#140]
One way to update a yaml file just on the command line (to sync it with the github repo) is to:
- metadata-delete the file
- metadata-load the file

by deleting e.g. the priority of this metadata file is lost, and it will be back to default.

Suggestion: add a --force-overwrite flag to metadata-load to just overwrite the metadata, but leave the rest, like enabled flag and priority as is.

**Comment by rseuster** [comment]
a replace function will be provided

**Comment by crlb** [comment]
-F/--force option implemented on group/cloud metadata-load.
