### ISSUE TITLE
Add aditional error feedback for keypair transfers

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#141]
There is currently no feedback when a keypair transfer fails leaving the user nothing but some messages in the logs to figure out what happened.

When performing the openstack command it can throw errors for many resasons:
Quota Exceeded (403)
Key Pair 'xyz' already exists (409)

and probably many others, the transfer function should at the very least return and display the openstack error message on the page.

**Comment by rseuster** [comment]
part of the re-write

**Comment by rseuster** [comment]
close
