### ISSUE TITLE
no default.yaml.j2 when creating a new group

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#142]
when creating a new group, defaults should be set. E.g. is the default.yaml.j2 missing, the new group
doesn't have any yaml files at all.

**Comment by kcasteels** [comment]
Should this default.yaml be empty or should it contain something useful? It seems to me it should contain sometime useful... but what? I'm not the expert in this.

**Comment by mhpx** [comment]
It should be https://github.com/hep-gc/cloudscheduler/blob/dev/default.yaml.j2  since that contains the basic stuff all VMs need to connect back to the configured condor pool.  We may need to store it in the DB somewhere as the 'master default.yaml.j2' or something to that effect.

**Comment by kcasteels** [comment]
default.yaml.j2 is now added to all new groups. Its using the file in /opt/cloudscheduler now. The file path is set as a variable dependent on the install path. This is currently not defined anywhere, so we will need to revisit this in the future.

**Comment by kcasteels** [comment]
Please test on csv2-dev2.

**Comment by rseuster** [comment]
works ! Thanks for the quick fix !
