### ISSUE TITLE
reducing limit on web interface wiped out all running VMs

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#144]
To free resources for Belle, I reduced the soft max limit from 1000 cores down to 950, later to 800.
This was at 3:24pm.

At this time, cloudscheduler terminated all running VMs and all VMs were lost.

I copied the watch log into
/var/log/cloudscheduler/watch_csv2.logging-incident

**Comment by mhpx** [comment]
the auto scaling happens within  the db / web frontend.

**Comment by rseuster** [comment]
hopefully fixed
