### ISSUE TITLE
Streamlined kill/retire process.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloudscheduler#147]
Four csv2_vms columns are involved in the kill/retire process: htcondor_partitionable_slots, htcondor_dynamic_slots, retire, and terminate. To ensure an orderly shutdown and termination of a VM under normal conditions:

1. UI and main tasks will set the retire=1.

The command poller action the following:

2. The retire process:
    a. retire=0 - VM is in use, do nothing.
    b. retire=1 - The VM may or may not be busy, but issue condor_off anyway and increment retire by 1.
    c. retire>1 -  condor_off has been issued "retire-1" times, wait for htcondor_dynamic_slots<1 || NULL.
    d. retire>1 and htcondor_dynamic_slots<1 || NULL and htcondor_partitionable_slots>0, issue condor_off and increment retire by 1.
    e. retire>1 and htcondor_dynamic_slots<1 || NULL and htcondor_partitionable_slots<1 || NULL, set terminate=1.

3. The termination process:
   a. terminate=0 - Do nothing.
   b. terminate=1 and htcondor_dynamic_slots<1 || NULL and htcondor_partitionable_slots<1 || NULL, call VM termination function, and increment terminate by 1.
   c. terminate>1, call VM termination function, and increment terminate by 1.

Under exceptional circumstances, eg. user wants to kill a VM, the UI or main tasks can effect an immediate kill by setting terminate=2. The command poller will then be execute task 3c.

**Comment by colsond** [comment]
Just to add to this we also have a "retiring" flag that's used to not re-issue the retire if it is already in that state and retire>1.

**Comment by colsond** [comment]
This is implemented on dev.
