### ISSUE TITLE
Update Condor status and track polling failures

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#148]
Since we allow for remote condors it no longer makes sense to have the system status poller track the status of the local condor process. Instead we should remove it from the status poller and introduce a couple new fields to the group table: last_machine_poll and last_job_poll, these will be updated on a successful poll.

The web frontend should remove the checkbox for condor and instead display a group specific message if the group's condor was unable to be polled in the last <configurable_time>.

We should also gather timeseries data on these events and use influx db to plot the outages. There will be specific lines logged in csmachines.log and csjobs.log indicated a failed poll of condor.
ex.

> Job Poller   - ERROR - Failed to locate condor daemon, skipping: unit-test-group-three.ca
> 2019-02-14 12:28:53,585 - Job Poller   - CRITICAL - 797 failed polls on host: unit-test-group-three.ca, Configuration error or condor issues
> 2019-02-14 12:28:55,374 - Command Poller - WARNING - Failed to locate condor daemon, skipping: unit-test-group-four.ca

These log messages can be adjusted accordingly to make them easier for whatever is picking them up for influxdb.

**Comment by kcasteels** [comment]
The condor status indicator has been replaces with a timeseries indicator on stable2.2. This will be backported to dev. We need to group specific condor status info.

**Comment by rseuster** [comment]
done
