### ISSUE TITLE
-cn option not honored in cli

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#150]
In "vm list" the "-cn" option doesn't seem to have any effect:
```
mebert@heplw65:~$ cloudscheduler vm list -cn cc-west-a -r 
Server: prod, Active User: <sqlalchemy.ext.automap.csv2_user object at 0x7f3b15d61278>, Active Group: atlas, User's Groups: ['atlas', 'belle', 'coca', 'colson-test', 'test', 'testing']

VMs:
+--------------------------+------------------------------------------------+
+ Key                      | Value                                          +
+--------------------------+------------------------------------------------+
| Group                    | atlas                                          |
| Cloud                    | arbutus-a                                      |
| Hostname                 | atlas--arbutus-a--1685--141349567223628-1      |
| VMID                     | 6e8784e3-6aa3-4279-990d-969e491deb26           |
| IPs                      | ['10.39.24.10']                                |
| Floating IPs             | []                                             |
| Authorization URL        | https://arbutus.cloud.computecanada.ca:5000/v3 |
| Project                  | ATLAS-Services                                 |
| Status                   | ACTIVE                                         |
| Flavor ID                | 480d6cad-0f7f-4714-82a8-0cd9151ed109           |
| Task                     | None                                           |
| Power Status             | 1                                              |
...
...
```

**Comment by crlb** [comment]
Hello Marcus, et al,

Tested issue this morning from my workstation to csv2-dev and csv2-dev2 and it appears to be working well. So the question is, what were you exercising? It would be better if you could also tell us the levels of both the client and server. The following command will do exactly that:

crlb@heplw49:~$ cloudscheduler -xA -s prod
Cloudscheduler command line, Version: stable-2.1.0 + 213 commits

Expose API requested:
  py_requests.get(
    https://csv2.heprc.uvic.ca/settings/prepare/,
    headers={'Accept': 'application/json', 'Referer': 'https://csv2.heprc.uvic.ca'},
    auth=('crlb', <password>),
    data={},
    cookies='<RequestsCookieJar[<Cookie csrftoken=JyM80UZyuPFnhTldrOcpMxclCemcTrMTaCr3ImppyQONzYa0GLBSEZVJXNKuvIgJ for csv2.heprc.uvic.ca/>, <Cookie sessionid=9yp2aj9wpav0e32frigfsfpicrz630w6 for csv2.heprc.uvic.ca/>]>'
    )

  Response: {
    active_user: <sqlalchemy.ext.automap.csv2_user object at 0x7f3b15c7b9e8>
    active_group: atlas
    super_user: 1
    user_groups: ['atlas', 'belle', 'test', 'testing']
    response_code: 0
    message: None
    version: Tag: stable-2.1.0
    }

Error: No object specified; use -h or -H for help.
crlb@heplw49:~$

Assuming that you were talking a current client to csv2 (as is the case in the example command), in the stable 2.2-rc we changed the way we pass "selector" fields from URL path modifiers to query strings, which stable-2.1 (csv2) does not process. So I would say that this is not a bug but a design change. If you had used a stable-2.1 client, it would have worked.
