### ISSUE TITLE
have "Cores Softmax" replace "Global Cores Quota"

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#156]
It would be good to have the user defined setting that can replace the "Global cores quota" retrieved from the cloud. "Cores Softmax" is not of any use currently, it would be good to have this setting doing the above.

How should it apply:
- setting replaces the Global cores quota retrieved from the cloud in all views/status pages
- if set, cloudscheduler will not try to use more cores than "Cores Softmax" - "Foreign Cores "
- if there are more cores used on the cloud than defined in Cores Softmax, scale down to have not more cores used on the cloud than allowed 
   - can happen due to foreign VMs

advantages: 
- automatic scaling for opportunistic usage
  -  if we can use 1000 cores opportunistic until other users need resources, cs would scale down automatically when users start up VM and scale up when there is no other activity
- for us, better automated resource distribution between Atlas and Belle 
  - have 1000 cores limit
  - in Atlas define lower "Cores Softmax", e.g. 960,  in Belle define 1000 cores
    - if Belle has no jobs, Atlas will use up to 960 cores
    - if Belle has jobs, it can use up to 1000-#Atlas-cores, e.g. 40 cores
       - cs sees that Atlas is over limit and scales down, Belle becomes under limit and scales up,...
- gives better handling for clouds that do not put in a real quota but tell it from time to time how much to use

**Comment by crlb** [comment]
The following changes completed:
1. view_available_resources amended to account for quota/softmax - foreign VMs.
2. New view_vm_kill_retire_over_quota created to indicate clouds that need scaling based on quota limits exceeded. To be used by the openstack command poller.
3. view_utils.py, containing the kill_retire function, moved to cloudscheduler/lib so as to be available to the openstack command poller for cloud resource scaling.

To do:
1. openstack command poller updates.
2. testing.

**Comment by rseuster** [comment]
if we now go this way, we need a minimum number of cores as well. scaling up in harvester is an extremely painful process once we are under a certain number of jobs / VMs.
Even with this in place I fear we won't scale up as quick as Belle II sometimes stops using VMs.

**Comment by rseuster** [comment]
This limit could be a percentage, if needed. I prefer absolute though

**Comment by MarcusEbert** [comment]
I don't think we need a minimum of cores implemented in cloudscheduler.

The softmax replacing the cloud quota is a general and experiment independent feature allowing to use  opportunistic resources until the user to whom the resources are allocated needs it again. 
A minimum would defeat that purpose.

Also, the way the quota/soft max is used then is that it will not go over that limit at all (even if no softmax is specified but the cloud quota is used together with #foreign VMs).
A fixed minimum would not allow that anymore.

The problem with Harvester is the scheduling in harvester and not cloud or cloudscheduler dependent. It should get fixed in harvester to not look to the number of running jobs but keep a minimum idle for each site. 

A minimum would also be cloud dependent and not project dependent. Atlas/Harvester does not need a minimum of x percent on each cloud/on a single cloud - it needs currently a minimum of cores in total to work a bit efficient. And that we can already achieve until Harvester uses a better scheduling without any minimum defined, e.g. by using a single cloud only for Atlas. 

We could include this minimum discussion in our Monday meeting after HEPiX.

**Comment by rseuster** [comment]
In a similar way I can argue that we don't need a "Cores Softmax", we work around a feature that the cloud doesn't announce it's actual quota:
We just ask CC-west to update their quota, which cloudscheduler then will obey.

We will always need some extensions to workaround deficiencies or take our special needs into account. cloudscheduler for example has no concept of allocations.

So, yes, currently we need a minimum Cores feature.

**Comment by MarcusEbert** [comment]
That's right, but that's not the main use case of the softmax - it is just useful for that CC does not update quotas.
The real use case for softmax is the use of opportunistic resources with automatic scale up and down, on any cloud. And it is not only the softmax introduction but also the change that the quota (from the cloud or softmax) is used as a max number of used cores on that cloud including foreign VMs.

Let's talk about it in a Monday meeting so we all better understand the need.

**Comment by rseuster** [comment]
That's again a feature tailored for our use case ;)

Not a general cloudscheduler feature. We need our own extensions to get the best usage for us.

**Comment by colsond** [comment]
Downscaling via vm poller using view_vm_kill_retire_over_quota & kill_retire implemented in dev as of commit e963535aed779369fbffdd33ab172758238b39ca.

**Comment by rseuster** [comment]
one done
