### ISSUE TITLE
on web page in VM views, sort by age is not correct

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#160]
When the VM view is open, then one can sort the view by age. However, the sorting is not correct:

example ages: 1321 15325 3239 4175 17808

expected sorting: 1321 3239 4175 15325 17808
current sorting: 1321 15325 17808 3239 4175

tested on: current prod instance

**Comment by kcasteels** [comment]
A new js function was added to properly handle sorting numeric values.
