### ISSUE TITLE
clouds without VMs not shown on status page

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#161]
Clouds that are enabled are not shown on the status page if there is no running VM on that cloud. A cloud appears on the status page as soon as there is a VM starting only. (on prod instance)
Before all enabled clouds where shown.

**Comment by tolkamps1** [comment]
Fixed by Colin per commit 8c9da26. 'view_cloud_status' was not including enabled clouds with no VMs.
