### ISSUE TITLE
project domain name and id not interchangable in python openstack API

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#165]
When attempting to add LRZ using a project domain id the openstackpoller was throwing authentication errors. It turned out this was because unlike some other parameters project_domain_name and project_domain_id are not interchangable when creating a session object. We will need to either add a field for project_domain_id in the clouds table, or manually catch the authentication error and try again using the domain id parameter instead of domain name.

**Comment by rseuster** [comment]
I would prefer to have a boolean flag which determines if this project_domain is given by name or by id. 

Or - could that be auto-detected ? If the string is 32 character long, and only contains 0-9a-f, then it is an ID, otherwise it's a name.

**Comment by crlb** [comment]
We have “cloud_type”.  If it’s “opennebula” use domain and id.

**Comment by rseuster** [comment]
The new cloud at LRZ is openstack, currently only for testing, no production

**Comment by crlb** [comment]
Still think cloud_type is the right answer.

**Comment by rseuster** [comment]
I tend to disagree.

Can you explain a bit ?

both cloud_types would be "opentack" and "openstack_id" ?

What about other combinations ? I guess for all variables from the v2, the user  can specify mix the configuration, e.g. use <var>_id or <var>_name interchangeably.
For v3 this seem to be not the case any more. If <var>_id must really be the <var>_id.

**Comment by crlb** [comment]
Mike and I have talked and we think we shouldn't guess or kluge, but should add the fields project_domain_id and user_domain_id to the csv2_clouds, so that the user can copy the credentials directly from their openstack "rc" file into the cloud definitions on CSV2. If the fields are populated, they should be used.

**Comment by rseuster** [comment]
DB is done, user interface missing

**Comment by rseuster** [comment]
to be confirmed that it's implemented everywhere. Please un-assign yourself and close the issue if confirmed

**Comment by rseuster** [comment]
based on the commits, this was done
