### ISSUE TITLE
openstack poller still runs on disabled clouds

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloudscheduler#168]
Log is being cluttered with messages about lrz cloud, but lrz cloud is currently disabled. Should the pollers skip disabled clouds?

**Comment by colsond** [comment]
The only reason i can think of to not skip them is to have the cloud metadata available. We could get around that with another signal though, trigger the poller when a cloud is enabled.

Another option is to suppress the logging for disabled clouds.

**Comment by rseuster** [comment]
What do we do if a cloud is disabled while jobs and VMs are still running, Are they killed or retired ?
In later case, if a cloud is just being disabled, we still need to poll it for running jobs and VMs.

Should we stop polling VMs when all VMs are gone.?

**Comment by mhpx** [comment]
Maybe selective based on each poller's function? suppress / skip ones like flavors, images, and keep doing vms and quota? disabling (or maybe shifting the level to being more verbose?) for disabled clouds sounds good too.

**Comment by rseuster** [comment]
I guess, we can close this now.
