### ISSUE TITLE
Job poller dies without exception when attempting to hold jobs on a remote condor

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#170]
I noticed this happening on dev with dev2 configured as one of the condors. The poller seems fine to poll the job list and all that but when it tries to issue the job action it dies without an exception and is restarted by the process monitor.

Looking at the condor logs on dev2:
> 03/22/19 10:53:33 (pid:2277705) AUTHENTICATE: handshake failed!
> 03/22/19 10:53:33 (pid:2277705) DC_AUTHENTICATE: authentication of <206.12.154.224:44307> did not result in a valid mapped user name, which is required for this command (478 ACT_ON_JOBS), so aborting.
> 03/22/19 10:53:33 (pid:2277705) DC_AUTHENTICATE: reason for authentication failure: AUTHENTICATE:1002:Failure performing handshake|AUTHENTICATE:1004:Failed to authenticate using KERBEROS|AUTHENTICATE:1004:Failed to authenticate using FS|FS:1004:Unable to lstat(/tmp/FS_XXXMc7VmW)

I'm not sure if we have GSI enabled on dev2 (didn't look like it in the config) but that doesn't seem to be the problem. In my search for similar issues i found this thread:
https://www-auth.cs.wisc.edu/lists/htcondor-users/2018-May/msg00048.shtml 
Looking at the log output it looks like it tries to authenticate via handshake, fails, attempts to authenticate via kerberos, fails again then finally tries to authenticate via FileSystem and fails again gives up and the client (poller) just dies.

The link above summarizes Filesystem authentication pretty well but I feel like that's not the type of authentication we should be using? Do we need to set up a cloudscheduler@csv2-dev user for dev2 to use it as a valid job queue on dev? I suspect we didn't see problems like this before because reading the job queue isn't a privileged command whereas editing a job ad is. Maybe this can be solved via condor configuration but the issue of the python bindings crashing on a failed authentication is probably worth reporting to the developers.

**Comment by colsond** [comment]
After some correspondence with the condor mailing list I was able to avoid the crash by updating to the newest versions of the htcondor python bindings. Instead of crashing it now reports an exception:
Error when performing action on the schedd.

which is more in line with what we should expect. We still need to figure out how to set up remote authentication for the cloudscheduler user:

03/27/19 10:46:43 (pid:3874338) DC_AUTHENTICATE: authentication of <206.12.154.224:49052> did not result in a valid mapped user name, which is required for this command (478 ACT_ON_JOBS), so aborting.
03/27/19 10:46:43 (pid:3874338) DC_AUTHENTICATE: reason for authentication failure: AUTHENTICATE:1003:Failed to authenticate with any method|AUTHENTICATE:1004:Failed to authenticate using GSI|GSI:5002:Failed to authenticate because the remote (client) side was not able to acquire its credentials.|AUTHENTICATE:1004:Failed to authenticate using KERBEROS|AUTHENTICATE:1004:Failed to authenticate using FS|FS:1004:Unable to lstat(/tmp/FS_XXXauUfSO)

If anyone is familiar with making remote users for condor I'd appreciate a push in the right direction.

**Comment by rseuster** [comment]
to be tested

**Comment by rseuster** [comment]
should be obsolete with rabbitmq agent for remote condors
and closing
