### ISSUE TITLE
webgui: changing something in cloud configurations will retire all VMs on that cloud

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#171]
what I did:
went to https://csv2.heprc.uvic.ca/cloud/list/?atlas#arbutus-a
changed the VM image to "cernvm4-micro-2018.10-1.hdd" and hit update

all VMs then immediately went into retiring state.

Also changing the cores limit on web gui will retire all VMs. command line works as expected, i.e. no VMs retire.

**Comment by kcasteels** [comment]
What happens with you adjust both the cores and ram via the command line?

**Comment by rseuster** [comment]
no VMs will then retire

**Comment by rseuster** [comment]
should be fixed now, but needs more testing. When I am back at UVic.

**Comment by rseuster** [comment]
seems to be working, closing
