### ISSUE TITLE
allow application credentials for authentication with keystone

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#174]
Talking with Jiri from Prague, we are wondering if cloudscheduler can use application credential for authentication.

His objective is, that his personal credentials to openstack are behind a SSO wall, so obviously, he doesn't want to give out his password, similar to the openstack installation at CERN.

This issue is just to collect possible solutions, not a request to implement anything yet.

**Comment by rseuster** [comment]
python api missing

**Comment by colsond** [comment]
Added in 2.9.0
