### ISSUE TITLE
Problems with switching versions.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloudscheduler#178]
From stable-2.2 to dev (stable-2.3):
- no /var/local/cloudscheduler
- no pip3 boto3

**Comment by colsond** [comment]
Not sure if this is the appropriate issue but here are some more things to keep in mind for updating ansible

- Python packages (can use pip3 freeze on our environment to get an exhaustive list)
- Signals directories
- moved/changed configuration (new service file name for celery, updated csv2_ssl.conf for apache)
- Host certificate copy (or a proxy copy) for for cloudscheduler user remote condor authentication

**Comment by rseuster** [comment]
close

**Comment by rseuster** [comment]
now really close
