### ISSUE TITLE
csv2-dev2: pulled in EC2 changes from dev ?

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#181]
there are two problems on csv2-dev2 right now:
- it seems changes for ec2 were pulled in into the default.yaml.j2 ?
in particular I needed to remove these lines:
```
# Pick a random collectorchildX, where X is a random number between 1 and 3.
# If you are using more child collectors, then increase the second parameter
# to macro RANDOM_INTEGER() appropriately.  Note it is assumed that CONDOR_HOST is
# defined to be the full hostname (or IP address) of your pool's central manager.
# COLLECTOR_HOST = $(CONDOR_HOST)?sock=collectorchild$RANDOM_INTEGER(1,3)

# If someone were to run a tool such as condor_status on an execute node, we want it to 
# query the top-level collector so it sees the entire pool.
# TOOL.COLLECTOR_HOST = $(CONDOR_HOST)
# STARTD_ATTRS = COLLECTOR_HOST_STRING group_name flavor cloud_alias
STARTD_ATTRS = COLLECTOR_HOST_STRING group_name flavor
```
Quite possible, I didn't need to touch the last line with STARTD_ATTRS.

Second - when assigning a floating IP, one shouldn't do a condor restart, because then the start up code would add lines line this at the end:
```
# PRIVATE_NETWORK_NAME=amazon-ec2-nova
# TCP_FORWARDING_HOST=208.75.74.188
```

This might also interfere with operation.

**Comment by mhpx** [comment]
No idea where the first part is coming from.  COLLECTOR_HOST isn't found in our yaml, so it's probably the default from the base condor_config and we actually need to add it to ours with the correct setting.

The 2nd part is apparently an old artifact that has always been in the yaml. Even for CS v1. And is part of the setup step for both ec2 and openstack - although the fact is prepends the "amazon-ec2-" part even on non-amazon clouds is an oversight that has gone unnoticed forever.

**Comment by rseuster** [comment]
COLLECTOR_HOST is definitely set in the test-dev2 project on csv2-dev2. A git history would now be nice !

**Comment by MarcusEbert** [comment]
This changes were made when testing remote condor using condor.heprc.uvic.ca with a large number of jobs.

The 2 lines make use of 3 different collector processes and ensure that the main one is queried for a list of all jobs.  To have it work, also changes in the config of the local condor  server are needed:
```
# Define sub collectors (in this case, we want 3)
# This will result in a condor_collector with sock names
# of collectorchild1, collectorchild2, collectorchild3.
use Experimental:CollectorNode(child1)
use Experimental:CollectorNode(child2)
use Experimental:CollectorNode(child3)
```

This was applied on condor.heprc.uvic.ca, but since it was not on the local condor it caused problems when the condor server for the group was changed again.

**Comment by rseuster** [comment]
closing
