### ISSUE TITLE
VMs under manual control shouldn't be retired due to limits

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#182]
while testing mv VM under manual control got deleted. These should be the very last ones being terminated.

**Comment by rseuster** [comment]
I guess this is not done any more. Colson - do you know ?

**Comment by colsond** [comment]
This should not happen, i'll double check that the flag is enforced.

**Comment by colsond** [comment]
From what I can tell this still shouldn't happen. When a vm appears in view_condor_host with the terminate flag set the first thing that is done is to check if the vm is under manual control:
`# we need the relevent vm row to check if its in manual mode and if not, terminate and update termination status
try:
    vm_row = db_session.query(VM).filter(VM.group_name == resource.group_name, VM.cloud_name == resource.cloud_name, VM.vmid == reso        urce.vmid)[0]
except Exception as exc:
    logging.error("Unable to retrieve VM row for vmid: %s, skipping terminate..." % resource.vmid)
    continue
if vm_row.manual_control == 1:
    logging.info("VM %s under manual control, skipping terminate..." % resource.vmid)
    continue
`
