### ISSUE TITLE
reducing quota: retire / kill VMs in ERROR first

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#184]
around 17:14:20, I reduced quota for otter on csv2 from 450 down to 410 cores, 5 VMs were in ERROR state. csv2 retired 4 of those and one unregistered.

**Comment by rseuster** [comment]
+1

**Comment by crlb** [comment]
view_vm_kill_retire_priority_age and view_vm_kill_retire_priority_idle both amended to ignore VMs with manual_control != 0.
