### ISSUE TITLE
time scale on time series wrong

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#185]
changing the time scale in time series doesn't change anything right now.

**Comment by rseuster** [comment]
This seems to happen only, if one makes time series when the detailed view is open.

**Comment by rseuster** [comment]
might have been a stale cache. closing

**Comment by tolkamps1** [comment]
Reproducible issue, but was fixed on dev branch with the rest of the x and y-axis issues. Steps to recreate on csv2:
            1. click on value to plot
            2. change range (eg. last 30 min)
            3. close plot
            4. click on value to plot
Wrong date range that cannot be changed is shown.
