### ISSUE TITLE
changing global configs should restart csv2

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#188]
changing e.g. max_start_vm_cloud in the global configs for csmain has no effect until csv2-main is restarted.
This means a restart of csv2-main should be triggered when changing something, or csv2 should be triggered to reload its config file.

**Comment by rseuster** [comment]
code is there, needs modifications in code

**Comment by mhpx** [comment]
https://github.com/hep-gc/cloudscheduler/commit/8be922540f9039a0ab80ceab772db1845225166d should resolve this using the newer refreshable config object.

**Comment by rseuster** [comment]
process monitor and pollers are both outstanding

**Comment by colsond** [comment]
The process monitor and the pollers have both been updated to use the new refreshable config for the stable-2.6 release.

The only place where this can still be a problem is if the CONDOR configuration gets changed on the fly. The machine and job pollers will need to be restarted to pick up the new configuration context but that is a separate issue so I'm going to close this for now.
