### ISSUE TITLE
Change Window title to something usefull

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#192]
Current behavior:
The title of the csv2 browser window is the same as the URL which is useless and can be long.

Proposed change:
Change the title to something static; e.g. use the name and the version as title.

Possible change:
in 
```web_frontend/cloudscheduler/csv2/templates/csv2/navigation_bar.html```
change 
```
<head>
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static "csv2/navigation.css" %}?{{version}}">
</head>
```
to
```
<head>
    {% load static %}
￼    <link rel="icon" href="{% static 'img/favicon.ico' %}">
￼    <link rel="stylesheet" type="text/css" href="{% static "csv2/navigation.css" %}?{{version}}">
￼    <title> Cloudscheduler {{version}}</title>
￼</head>
```

see https://github.com/hep-gc/cloudscheduler/commit/eeb995265f05c8f883814bbdb6dfdc17ae5ad92c

**Comment by rseuster** [comment]
we had this already and changed it back to what it is now.
<title> is not the right thing to do here. The tab name should change, not the whole window title - IIRC the problem we had. It should also contain the hostname to distinguish the various instances. I thought this was done via the favicon, but this disappeared for me on csv2a.

**Comment by MarcusEbert** [comment]
<title> is the right place to change it; otherwise the full URL will be used for tab and window title when the tab is the active tab; at least in Chrome.   Tab name and window title should not be the full url but it should be static.

favicon shows in different colors which host is used; so the title can be something different. 
Instead of "Cloudscheduler", which is what is shown, it could also be the hostname, or the first part of the hostname, or anything else that is static. Thought other groups may not have any need to distinguish between different cs instances, so favicon may be enough for that. 

{{version}} should also be just the version and not contain "Version:" in it, but that's a different issue. 

The proposed change was just an example, anything static and meaningful would do.

**Comment by kcasteels** [comment]
The window title is now set to the short hostname, so for csv2-dev.heprc.uvic.ca the short hostname would be csv2-dev.

**Comment by rseuster** [comment]
done and won't fix. Hahaha
