### ISSUE TITLE
use "Cores Softmax" in status view and consistent usage of style

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#193]
Current status:
If there is a "Cores Softmax" set for a cloud, it is not visible in the status page.

Example: 
On csv2a, for Arbutus the softmax is set to 1650 while 1600 foreign cores are used and 48 native cores - but the "Cores Global" shows that that the used cores are far from the maximum.

Also Global cores and global VMs are shown as graphic only in the main status view, while it is shown as numbers for "Native Cores", "Foreign Cores", and "Foreign VMs".

Proposed change:
On the status page
* instead of showing the quota obtained from the cloud for Global Cores max, use the softmax if set
* remove the graphics for "Global Cores" and "Global VMs"
* display the plain numbers currently used instead of the graphics in the unexpanded view, same as for native and foreign tabs on the left
* keep the expanded view like it is currently (showing currently used and max usable)
* show "Global VMs" first, then "Global Cores", and at last "Global RAM, same as it is done for all foreign properties

**Comment by kcasteels** [comment]
I've made these changes. Have a look and see if its what you'd like Marcus.

**Comment by MarcusEbert** [comment]
Looks good on csv2-dev
