### ISSUE TITLE
ec2 testing issues

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#202]
server: csv2-dev2
group: test-dev2
cloud: amazon-east

Problems:

1.  ```cloudscheduler ec2 images -cn amazon-east``` shows the images, but the only identifier is ID which is ```ami-....```.  Using ```cloudscheduler cloud update -cn amazon-east --vm-image ami-....``` gives an error: ```Error: CV-01516 cloud update, "amazon-east" failed - specified item does not exist: vm_image=ami-..., group_name=test-dev2, cloud_name=amazon-east.```
```--vm-image``` needs to be the name but that is not displayed.
1.1 The cli options and the error response use different style, e.g. "vm-image" vs "vm_image" which can be confusing to a user. 
2. The name of the image is 'CERNVM3' but when specifying ```cloudscheduler ec2 images -il "'CERNVM3'" -cn ....``` it gives an error:
```Error: EC2-00071 ec2 images, value specified for "like" must be all lower case.``` 
That can be confusing because the name on EC2 uses upper case letters.  Also the image name needs to be upper case still when specifying which image needs to be used for the cloud (```--vm-image "'CERNVM3'")
3. Within the database, a keyname was set for the cloud and for the group which did not exist on amazon, but this was not visible in the web interface or the cli query, only directly within the database
4. A starting spot-instance is placed into ERROR state instead of starting.

**Comment by rseuster** [comment]
re 1: ec2_poller use ami for name if name is empty
      include name in lists of ec2 images
re 2: review case - converted to lowercase in DB already
re 3: ssh vm key set - from where ? Marcus to re-create the issue
re 4: probably fixed by Colson

**Comment by rseuster** [comment]
should we wait for the anniversary ? Naeh - closing now
