### ISSUE TITLE
remove yaml comments - try yaml load and dump

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#205]

**Comment by mhpx** [comment]
So it's not the yaml itself that has the comments (or bulk of the comments) but rather the contents of the files we're writing. When the yaml is parsed, those comments are being treated as part of the contents and is all part of a large string. So there's simple way to remove those within the yaml lib.

**Comment by mhpx** [comment]
Stripping comments will be a stopgap measure so the solution is to support having the !#include content-type: text/x-include-url style like we used for opennebula
