### ISSUE TITLE
automatic retire not working in specific situation

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#209]
on csv2a (2.4-stable):

situation on arbutus (cores) before changes:
cloud quota: 5000
usable cores: 2000
softMax: 2000
Running: 2000
Retire: none

changes: 
Softmax set to 1200
usable cores set to -1

expected behavior: 
VM equal to 800 cores go into retire state

observed behavior: 
No change for number of running or retired VMs

additional change:
usable cores set to 1200

After that, VMs equal to 800 cores get retired.

**Comment by rseuster** [comment]
let's close this
