### ISSUE TITLE
clear message from web page

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#21]
after modifying a cloud and switching to another cloud, the OK from first cloud still on screen.
![screenshot from 2018-05-03 11-38-05](https://user-images.githubusercontent.com/16807038/39596280-b03d5ff4-4ec6-11e8-86ce-d2a3221f2b7e.png)

**Comment by colsond** [comment]
updates ?

**Comment by kcasteels** [comment]
This was fixed long ago.
