### ISSUE TITLE
CSV2 variable substitution and metadata names

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#211]
On csv2a:

CSV2 variables, like {{cs_condor_host}}, are only substituted in default.yaml.j2 and csv2htc.yaml.j2 it seems, which would exclude the use in other parts of the metadata and also have the naming of those 2 files fixed.

Feature request: 
- allow variable substitution in all metadata parts 
- and do not force a specific name of the metadata, e.g. allow name "default" instead of "default.yaml.j2".

**Comment by mhpx** [comment]
they should get applied in any yaml files that ends with a .j2

**Comment by MarcusEbert** [comment]
Ok, thanks.
