### ISSUE TITLE
cli error when try to edit metadata

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#212]
mebert@heplw65:~/metadata$ cloudscheduler metadata list -g belle
Server: prod, Active User: mebert, Active Group: belle, User's Groups: ['atlas', 'belle', 'test', 'testing']

Active Group/Metadata:
+-------+--------------------+-------------+-------------+----------------+
+ Group | Metadata Filename  | Enabled     | Priority    | MIME Type      +
+-------+--------------------+-------------+-------------+----------------+
| belle | accounting         | 1           | 0           | cloud-config   |
| belle | belle              | 1           | -1          | cloud-config   |
| belle | benchmark          | 1           | 0           | cloud-config   |
| belle | cernvm-data.txt    | 1           | 0           | ucernvm-config |
| belle | condor-config      | 1           | -1          | cloud-config   |
| belle | csv2htcondor_check | 0           | -10         | cloud-config   |
| belle | default.yaml.j2    | 1           | 0           | cloud-config   |
| belle | monitoring         | 1           | 0           | cloud-config   |
| belle | ssh-fix.yaml       | 1           | 5           | cloud-config   |
| belle | ssh_key.yaml       | 1           | 0           | cloud-config   |
| belle | usersshkey         | 1           | -1          | cloud-config   |
+-------+--------------------+-------------+-------------+----------------+
Rows: 11

echo $EDITOR
/usr/bin/nano -w

echo $VISUAL
/usr/bin/nano -w

 ls -l /usr/bin/nano 
-rwxr-xr-x. 1 root root 205888 May  2  2014 /usr/bin/nano

cloudscheduler metadata edit -g belle -mn belle
Traceback (most recent call last):
  File "/hepuser/mebert/opt/bin/cloudscheduler", line 491, in <module>
    main(sys.argv)
  File "/hepuser/mebert/opt/bin/cloudscheduler", line 413, in main
    gvar['actions'][gvar['object']][1][gvar['action']](gvar)
  File "/hepuser/mebert/Git/cloudscheduler/cli/bin/csv2_metadata.py", line 535, in edit
    return metadata_edit(gvar)
  File "/hepuser/mebert/Git/cloudscheduler/cli/bin/csv2_group.py", line 399, in metadata_edit
    p = Popen([editor, '%s/%s' % (fetch_dir, response['metadata_name'])])
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/nano -w': '/usr/bin/nano -w'

**Comment by crlb** [comment]
Your EDITOR environment variable is invalid, see https://wiki.archlinux.org/index.php/Environment_variables - the variable must be set to the executable command name or path of an installed editor without options. Your EDITOR variable is set to "/usr/bin/nano -w"; the "-w" option cannot be specified here. If you wish to suppress line wrapping, use a "nanorc" file and set "nowrap" or "softwrap"

**Comment by MarcusEbert** [comment]
Strange, it works anywhere else  $EDITOR or $VISUAL is used in bash.

**Comment by crlb** [comment]
fixed 85592152c25aa053bf997a37368a4cfc3cb2feea
