### ISSUE TITLE
provide kill idle vms functionality for problem VMs (VMs with an expired certificate)

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#221]
We've encountered a problem with ATLAS where the condor worker certificate expired after jobs had started and as such csv2 is unable to issue commands to the machine (condor_off). As far as we've been able to tell there isn't a simple way to fix the authentication on the machines without setting a floating IP, ssh'ing into the machine to update the key and certificates. To get around this there is logic in the machine poller to terminate a vm that has no primary or dynamic slots and also had the retire flag set >=1, but since the priamry slots never goes to zero the terminate is never set.

A way around this problem is to terminate vms that have the retire or terminate flags set and 0 dynamic slots (no jobs running). Or if we only wanted this functionality temporarily we could set a timestamp in the machine poller config that checked this logic and that the start time of the VM was older than the timestamp. This means that we could set this timestamp and it would clear out any problem vms and then any new vms coming online would ignore this logic.

**Comment by colsond** [comment]
We've added some logic that should stop us from running into these types of errors but we should probably revisit if we want some sort of vm kill-override functionality to forcefully terminate a vm regardless of the slot counts.

**Comment by rseuster** [comment]
closing
