### ISSUE TITLE
Track network load in addition to CPU RAM and DISK usage

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#222]
We should track the network traffic as well since it may become a limiting metric for our server when both condor and httpd are experiencing a heavy load (things like glint image transfers will also have a big impact).

**Comment by colsond** [comment]
After experiencing an outage on arbutus and discovering a bug in the openstack poller as a result it has become apparent that it would be a good idea to keep some timeseries data about the availability of the registered clouds.

We could accomplish this by adding a status field to the csv2_clouds table and having the openstack/ec2 vm poller update each row with the current status on each polling cycle and then have the timeseries poller inspect these rows and report the status to influxdb.

**Comment by rseuster** [comment]
this is the RT - the response time. closing
