### ISSUE TITLE
Use timeseries database for status page data

### ISSUE THREAD

**Issue by kcasteels** [hep-gc/cloudscheduler#223]
Instead of querying the MariaDB for status page data (which is shared with the rest of the CSV2 system) we could get the data from the timeseries InfluxDB. This would decease load on the main DB, especially if many users open the status page at once. All of the required data is already in the InfluxDB, but we would need to build equivalent "views" to show the data on the status page.

**Comment by rseuster** [comment]
this is also part of the user-webpages I believe. added to EPIC ticket.
