### ISSUE TITLE
VMs report certificate expiary 

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#224]
We experienced an issue where the condor worker certificate on the VMs expired causing authentication to fail when csv2 tried to issue a retire request.

To remedy this it would be ideal to update the csv2htc.yaml to use an oppenssl command to monitor the certificates expiry status and if it is going to expire within a day report back to csv2 using the same method as startd-errors. When startd-errors gets this message it can update the retire flag on the reporting vm so that the VM starts retiring before the certificate expires and it becomes impossible to do so.

**Comment by rseuster** [comment]
was this a very long running VM ?

**Comment by colsond** [comment]
I don't recall how long the arbutus vms were running, but the ones from otter are over a month old. Regardless of the age- until we updated the yaml with the new version of the certificate all new vms coming up had the same problem.

**Comment by colsond** [comment]
Certificate monitoring has been implemented in the stable-2.6 release, I'm going to close this issue for now as the relevant information is now made available to the user via the web interface.
