### ISSUE TITLE
add .forward to ansible

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#225]
Quite a few cronjobs etc fail unnoticed. The notification is typically an email to root, but noone reads them, so these problems are undetected for a long time, until they show up in a different context and hurt us.

Please add a .forward to root's homedirectory into the ansible installation scripts. We could create an account with one of the free mail hosters, since noone will volunteer to use their own mail address.

BTW - I added a .forward to the main servers hosting the services I am interested in, csv2a and elk for example.

**Comment by MarcusEbert** [comment]
Would be good to have the content of the ".forward" be an admin config option within csv2.

**Comment by crlb** [comment]
New library playbook "configure_root_mail_forwarding.yaml" plus template using ansible variable "admin_email" added.

Tested on csv2-dev.

**Comment by rseuster** [comment]
where ? Since it's now assigned to me, I have to check

**Comment by rseuster** [comment]
playbook looks ok to me, assigning to Marcus, in case he wants to follow up on the config option in csv2.
What about the other accounts we utilize ? cloudscheduler, condor ?

**Comment by rseuster** [comment]
think that's done
