### ISSUE TITLE
automatic retire logic when same cloud multiple times used in same project

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#227]
We use arbutus twice in Atlas, one with 8c flavor and the other one with free flavor selection depending on jobs. When the softmax is reduced, both are affected in the same way, e.g.:
arbutus: softmax=1600,  800 cores used, priority 0
arbutus-nf: softmax=1600, 800 cores used, priority -1

(This scenario can also happen when there are different alias for one type set to give some jobs a specific environment while all others get automatic flavor selection.)

Now reducing the softmax to 800 for both, will result in an automatic retire of all cores on arbutus and arbutus-nf. 
Expected behavior would be that 800 cores on arbutus+arbutus-nf in total would get retired, not 800 on each. Priority of each entry could be taken into account, e.g. in the above case first any cores get freed up on arbutus (priority 0) and if more are needed then continue on arbutus-nf; and for entries with the same priority an equal amount should get freed up on both.

**Comment by rseuster** [comment]
non-standard use case, won't fix
