### ISSUE TITLE
csv2-dev2: detailed web display wrong

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#230]
See attached screen shot
![Screenshot from 2019-08-09 10-18-05](https://user-images.githubusercontent.com/16807038/62796998-6a6b0900-ba8f-11e9-954c-ff9562316ffd.png)

Totals is shown in one of the clouds of group "testing" and used condor partitions for clouds missing

**Comment by MarcusEbert** [comment]
Did you expand both rows? Looks like only one is expanded.

**Comment by rseuster** [comment]
I only expanded the "Totals". This is what you get, try for yourself. Jobs are now submitted 3 mins past the hour.

**Comment by MarcusEbert** [comment]
Ah, I see what you mean. It wasn't clear from the initial text. While the last line "Total", which is the total for all clouds/projects, shows the condor_slot usage, the "Total" for each project does not.

**Comment by rseuster** [comment]
let's close this one
