### ISSUE TITLE
automatic flavor selection

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#232]
Does the **automatic** flavor selection takes also the instance quota into account ?

For example on a cloud with an instance quota of 10, cores quota of 80, X-core flavor has X times the resources than the single core flavor, and 100 single core jobs in the queue:  
Would cloudscheduler boot 10 single core VMs using only 10 cores, or 10 8-core VMs using all 80 cores?

**Comment by crlb** [comment]
Flavor selection is done by view_groups_of_idle_jobs.
The instance quota (VMs_max, as well as other quotas and limits) is referenced and respected in view_avaiailable_resources. 

So the answer is: indirectly, Yes.

**Comment by rseuster** [comment]
flavour exclusions
