### ISSUE TITLE
uniform display of jobs

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#237]
on csv2a (stable-2.5+1commit), the expanded group line read for condor jobs:
```
Group	Jobs	 Idle  Running	Completed	
atlas▴	1125	358	 739	28
                1c: 319	427✕1c	14✕1c	 	 
                8c: 39	312✕8c	14✕8c
```
To have a uniform way to display jobs, maybe change    
1c: 319 -> 319x1c
8c: 39  -> 39x8c

**Comment by kcasteels** [comment]
I've improved the jobs detail on csv2a (stable-2.5). Does it look fine now?

**Comment by MarcusEbert** [comment]
Looks good to me - Thanks!

**Comment by MarcusEbert** [comment]
It seems the changes are not in 2.6 anymore.

**Comment by rseuster** [comment]
closing
