### ISSUE TITLE
"save plot" button for time series

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#239]
wondering how easy it is to really save the time series plot as a png file.
This is for making plots for e.g. either talks or to highlight problems and be able to
discuss later easily by just showing this plot.

very low priority

**Comment by rseuster** [comment]
added to epic

**Comment by MCatherine1994** [comment]
Added an arrow down button next to the close plot button, and by clicking on it, it will download the current plot with the legend:
![Screenshot from 2021-09-21 13-36-01](https://user-images.githubusercontent.com/23131735/134243964-1e386a9b-7bd3-41e0-afcd-a28613b0ff61.png)

Downloaded plot looks like:
![newplot](https://user-images.githubusercontent.com/23131735/134244031-e0e7ca0c-f680-46ed-b658-93bc33ff3141.png)

We could specify the width, height, format, name of the downloaded image, currently using: {format: 'png', width: 800, height: 600, filename: 'newplot'}, wondering if we want to set them to any specific value?

reference reading: we are using the [plotly](https://plotly.com/javascript/getting-started/) javascript library to do the timeseries plot, and it has a [downloadiamge](https://plotly.com/javascript/plotlyjs-function-reference/#plotlydownloadimage) method we could use directly

**Comment by MarcusEbert** [comment]
for the size: It should be big enough to be included in publications or in talks and shows there a good quality. For the ratio of the sides, best would be to be able to specify it; by default it should be a good format for talks, 16:10 maybe for the plot and ~2:1 including the legend.
What is the current ratio for the display in csv2, is it ~4:1?

**Comment by MCatherine1994** [comment]
current csv2 web shows the plot with a fixed height 340px, but the width changes while the browser window size changes. I tried to make the width:height ratio to 2:1 and 2.5:1 for the downloaded image:
width: 1200, height: 600:
![newplot (1)](https://user-images.githubusercontent.com/23131735/134254987-ec3603a5-92ec-449a-b480-ec72fe84e26c.png)

width: 1500, height: 600:
![newplot (2)](https://user-images.githubusercontent.com/23131735/134255015-23b54e6b-41ba-44dd-a737-27cb095a27f4.png)
