### ISSUE TITLE
APEL accounting: need 4 new entries in database

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#241]
Looking at what needs to be provided to APEL for their cloud accounting, there are 4 numbers missing in the cloudscheduler DB, in brackets their type:
- NetworkInbound [int]/ GB received
- NetworkOutbound [int]/ GB sent
The other two are benchmark related:
- BenchmarkType [varchar(255)], e.g. HEPSPEC06
- Benchmark [Decimal]

We could use condor to report all these numbers back, similar to what we already do for Belle to get the job status back into our ELK instance. This is rather trivial to do and gets updated automatically every 15mins (configurable) and is accessible via simple condor commands asking then for these attributes.

For accumulating these we could store them in currently unused archive tables in the database.

**Comment by rseuster** [comment]
caso (https://github.com/IFCA/caso/blob/master/doc/source/installation.rst)
uploads data defined in this wiki (PDF on the wikie page):
https://wiki.egi.eu/wiki/Federated_Cloud_Technology#Accounting

**Comment by colsond** [comment]
I think this has been implemented? Anything else to do here or can we close?

**Comment by rseuster** [comment]
closing
