### ISSUE TITLE
csv2-dev2: retiring / killing VMs from "Totals" operates only on first cloud

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#243]
When opening the detailed view of the "Totals" for a group and issuing e.g. a retire or kill
will then retire or kill only VMs in the first cloud, not for all clouds.

**Comment by rseuster** [comment]
might or might not be fixed. should test after the update is finished.

**Comment by colsond** [comment]
The VM-overlay needs a full functional audit.
