### ISSUE TITLE
csv2-dev2: retiring doesn't work

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#244]
8 VMs on otter are in retiring state since yesterday. However condor doesn't retire them, they are still "Claimed busy" and process jobs.

**Comment by colsond** [comment]
This was an issue with the user running the csv2-htc-agent not having a valid proxy and thus was unable to communicate with the condor collector. Commit 25cbe629bd99d9efdd6b29d8dd4b12e69b3d23df updates the agent and cs-machines to better report when the agent is in error so it will be easier to detect this type of error via the web display in the future. Once the user running the agent had a valid proxies retires continued.
