### ISSUE TITLE
check important proxies if GSI enabled

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#249]
We should check proxies of important accounts on the csv2 host. One of them just expired and caused trouble.
```
[root@csv2a ~]# grid-proxy-info -timeleft 
2590535
```
Assigning currently to Colson, we can discuss during next Monday meeting what to do with it.

**Comment by colsond** [comment]
Sounds like something we could easily add in the gsi poller. Perhaps it would be a good feature to have a configuration option to set the users we'd like to check for valid proxies. We could add in the csv2 system requirements as the defaults.

I also think we could change the web display(see below) to consolidate these two columns to one status and update the error messages to say which certificate or proxy is having a problem.
![image](https://user-images.githubusercontent.com/6413402/65806478-878e9080-e13e-11e9-8fa9-ae4191279e2f.png)

**Comment by rseuster** [comment]
I like that collapsing of columns - we can still show them separate in the detailed view.

**Comment by MarcusEbert** [comment]
This is something that is independent of the condor but needs to be on the local machine where csv2 runs. All condors didn't work anymore when the root cert on csv2a expired.
I think it would be better to have it on the bottom with all the other status signs for the local machine.

**Comment by rseuster** [comment]
Actually, it's more complicated. You need valid proxies on the machine that runs cloudscheduler, but the condor user on the condor host also needs a valid proxy.

**Comment by MarcusEbert** [comment]
But only on the cloudscheduler machine itself. The condor user on bellecs does not need a proxy and also other gsi condors do not need this.

**Comment by rseuster** [comment]
If your remote condor has gsi, you'd need that too. The retire command is issued via htc_agent on the remote condor

**Comment by rseuster** [comment]
And it was the cloudscheduler proxy that fixed the issue, not the root one. Nothing runs as th root user, what cloudscheduler is concerened

**Comment by MarcusEbert** [comment]
We need to have a deeper look into this.

The cloudscheduler proxy did not expire today, that's why I only updated the root one initially.
But seems it needed to get recreated too. 

The communication between remote condor servers and worker nodes should not require a proxy, only the certificate in the grid-mapfile. 

Good thing to talk about in the Monday dev meeting.

**Comment by rseuster** [comment]
The proxy of the cloudscheduler user  was expired when I checked it. After re-newing it, things started to work again.

**Comment by colsond** [comment]
Is there still action to take on this issue or can I close it now that we plan on moving away from proxies?

**Comment by rseuster** [comment]
please close
