### ISSUE TITLE
run cvs2-htc-agent as user, not as condor

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#252]
the cvs2-htc-agent is the only part of our system that runs as the condor user. Only for the condor and the root user, usercerts and userkeys won't be used for authentication, so one needs a proxy for these two users.

For csv2-htc-agent on the csv2 machine, run the agent as the cloudscheduler user (Rolf).

For remote csv2-htc-agents, run the agent as a configurable user, the admin of the remote condor then must ensure that that user has a working usercery/key (recommended) or proxy (Marcus).

**Comment by rseuster** [comment]
target is 2.6.1

**Comment by MarcusEbert** [comment]
The condor user does use certificates when there is no proxy. It uses GSI_DAEMON_CERT and GSI_DAEMON_KEY.  Only root can't use it since the key is owned and readable by condor only.

**Comment by rseuster** [comment]
GSI_DAEMON_CERT and GSI_DAEMON_KEY are used for daemons / services run under the condor user. We were using the condor user to run "user commands" via the python ABI. In this case, these files are _not_ used, and the commands fail. For all other users (except root and condor apparently) files in the .globus directory are also read and used if there.

**Comment by colsond** [comment]
Perhaps if we are running the agent under the cloudscheduler user we could maintain a user cert/key on the csv2 host and have our web service supply proxies for reregistered remote agents that need one for gsi. This way we wont need a complicated cron task to put a cloudscheudler certificate proxy on all the condor servers. It would let cloudscheduler make sure the agents had what they needed to run as long as the csv2 host had a valid certificate.

The condor admin would still need to add cloudscheduler as a valid condor user- I don't think that part could be automated on a remote host. The only reason we are able to do it on the csv2 host is because we have a symlink in condor config.d to a file owned by the cloudscheduler user.

**Comment by MarcusEbert** [comment]
Test on csv2-dev2:

```
bash-4.2$ id
uid=994(condor) gid=991(condor) groups=991(condor),18218(cloudscheduler)
bash-4.2$ condor_q


-- Schedd: csv2-dev2.heprc.uvic.ca : <206.12.154.223:9618?... @ 10/02/19 13:49:02
OWNER   BATCH_NAME               SUBMITTED   DONE   RUN    IDLE  TOTAL JOB_IDS
seuster CMD: job-testing.exec  10/2  13:35     13     12      _     25 125600.4 ... 125626.1
seuster CMD: job-dev2.exec     10/2  13:45      _      4      _      4 125628.0 ... 125632.0

16 jobs; 0 completed, 0 removed, 0 idle, 16 running, 0 held, 0 suspended
bash-4.2$ grid-proxy-info

ERROR: Couldn't find a valid proxy.
       globus_sysconfig: Could not find a valid proxy certificate file location
globus_sysconfig: Error with key filename
globus_sysconfig: File does not exist: /tmp/x509up_u994 is not a valid file
```

I became condor, run condor_q as a user command  and it works without a proxy because it automatically uses for all QUEUE_SUPER_USERS the GSI_DAMEON_CERT/KEY it seems.
Am I missing something?

**Comment by rseuster** [comment]
interesting . Something has changed from this morning, when it was definitely not working. Have to leave soon, will be offline for a while.

**Comment by MarcusEbert** [comment]
I leave the condor proxy removed for now on csv2-dev2.

**Comment by rseuster** [comment]
try again. It was now using the .globus cert/key. I renamed it.

**Comment by MarcusEbert** [comment]
funny....
```
bash-4.2$ id
uid=994(condor) gid=991(condor) groups=991(condor),18218(cloudscheduler)

bash-4.2$ condor_q -debug
10/02/19 14:04:12 authenticate_self_gss: acquiring self credentials failed. Please check your Condor configuration file if this is a server process. Or the user environment variable if this is a user process. 

GSS Major Status: General failure
GSS Minor Status Error Chain:
globus_gsi_gssapi: Error with GSI credential
globus_gsi_gssapi: Error with gss credential handle
globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order.
Valid credentials could not be found in any of the possible locations specified by the credential search order.
Attempt 1
globus_credential: Error reading host credential
globus_sysconfig: Error with certificate filename
globus_sysconfig: Error with certificate filename
globus_sysconfig: File is not owned by current user: /etc/grid-security/hostcert.pem is not owned by current user
Attempt 2
globus_credential: Error reading proxy credential
globus_sysconfig: Could not find a valid proxy certificate file location
globus_sysconfig: Error with key filename
globus_sysconfig: File does not exist: /tmp/x509up_u994 is not a valid file
Attempt 3
globus_credential: Error reading user credential
globus_sysconfig: Error with certificate filename: The user cert could not be found in: 
1) env. var. X509_USER_CERT
2) $HOME/.globus/usercert.pem
3) $HOME/.globus/usercred.p12
```
So as a user command with id condor, it tries to use the hostcert/key which of course doesn't work for the condor user, while for root it doesn't get used...

I need to think a bit about what's the best to do without using proxies - ".globus/" seems to be usable

**Comment by rseuster** [comment]
darn, I guess I know what happened when my tests failed for the condor user.
With su et al you don't always get a new login shell, sometimes you keep your old environment, and in particular $HOME could point somewhere else.

Let's discuss Monday what to do here. .globus seems to be working. BTW they contain the letsencrypt cert/keys :smile

**Comment by rseuster** [comment]
closing. run as condor. pragmatic.
