### ISSUE TITLE
Using cloud-wide resources opportunistically

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#258]
Currently using Softmax, different projects in cloudscheduler can share resources in a way that a project with lower priority can use nearly all resources while the project with higher priority has no jobs.  To work, cloudscheduler needs to have access to the project where it should use opportunistic resources. Due to this, it is currently not possible to use cloud-wide free resources.  
This issue should track possible solutions to make opportunistic use of all free resources.

In any case to make use of all resources, administrator access to a cloud is needed. Since administrator access is not given out, the local administrator needs to provide in an automated way the information needed to scale up or down. 

One possibility is to have a cloud quota == total number of vcpus in the cloud and use the same Softmax mechanism that is already implemented to use less than the total number of vcpus.

1) local cloud admins provide a dynamic number for Softmax according to the local resource needs, e.g. 75% usage of resources at all time => Softmax value=0.75*total_vcpus - other_users_vcpus

This number can be read out directly by cloudscheduler,e.g via curl, or a user process queries the number from the cloud and set it via the cloudscheduler CLI.

Advantages of a user process putting in the softmax instead of cloudscheduler itself:
* Softmax put into cloudscheduler can be adjusted to lower values if needed
* multiple projects using the same cloud could get a different softmax so that the above discussed sharing of resources between different cloudscheduler projects is still possible
   * e.g. on arbutus  Belle could get 100%  of the dynamic softmax while Atlas gets 90% to keep the scaling between the projects working

**Comment by MarcusEbert** [comment]
First testing implemented for otter-cloud and Atlas/Belle on csv2a: 

**cloud-admin:** 
- get all and used cores via ``openstack hypervisor stats show``
- decide on how many of the total cores could be used opportunistically
  - for example 75% to leave room for others to start VMs
- write numbers in  file
  - propose 3 lines: total CPUs, used CPUs, max percentage to be used
- make file available to csv2-admin 
  - e.g. via curl/wget from the openstack http server
 
**csv2-admin:**
- get the file from the cloud-admin
- use csv2 cli to get the number of used cores within the cloud-project 
  - csv2-own used cores
- get used cores by others: *cloud_used_cores - own_used_cores*
- *softmax = allCPUs x percentage - others_used_cores*
   - define own ratio for Atlas and Belle:
      - *softmaxBelle = softmax x ratioBelle*
      - *softmaxatlas = softmax x ratioAtlas*
- use csv2 cli to set new softmax for each Atlas and Belle

**for otter-cloud*: 
- 75% opportunistic usage set
   - total CPUs number varies due to machines getting disabled in otter
      - similar like for outages on a cloud or bringing in new HVs
- softmax: ratioAtlas=90%  ratioBelle=100%  to allow for additional opportunistic scaling between Atlas and Belle


Current implementation very simple and for testing only, but works.

**open question:** How often should an update happen?
- from a cloud-admin point of view
- from a csv2 admin/project admin point of view
- influence of used VM flavor  and single core vs multicore jobs)

**Comment by colsond** [comment]
Implemented via CLI
