### ISSUE TITLE
More efficient scheduling in csmain

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#268]
Colin and I have been refactoring a lot of csmain as a result of the bad data being passed around when trying to create boot volumes for new VMs. In our restructuring we have found some opportunities for more efficient scaling up of new VMs.

Currently we identify if VMs need to be booted for a group and boot up to the configured max VMs (5) for that group on a cycle then move on to the next group- In this way we ensure that the resources are shared between groups when there is an overlap between clouds. However, this means that on a given booting cycle there may be clouds that aren't even considered for booting even though they are not busy. The change being proposed is to loop over the groups multiple times until all clouds in the group have been considered for booting additional VMs.

Before I get into some of the details we need to keep in mind the following parameters:
1. Cloud priority, this is important in the case where we want to max out our private clouds resources before tapping into clouds like amazon or azure that come with a pricetag.
2. Target cloud, Target alias - Since these may differ by groups of idle jobs the list of available clouds may differ for each group of jobs.
3. Groups of idle jobs, since there is no limit of how many groups there can be we may end up in a situation where there are more groups of jobs than clouds to boot on resulting in one or more groups of jobs getting starved out (this is a problem in current csv2 as well)

The idea would be to continue looping over the groups, groups of idle jobs, and the cloud-flavors associated with the groups of idle jobs. First we start looping over groups, get the first grouping of jobs, get the highest priority cloud-flavor for that group of jobs and attempt to boot there, if we are unable move on to the next cloud-flavor until we find one capable of booting new VMS. At that point we boot the vms, update our core counts, save our current indexes for the group (group of idle jobs index and cloud-flavor index) and move on to the next group. We do this for all groups and then return to the first one and begin again at our saved indexes. This cycle continues until we have looped over all of the possible cloud-flavors at which point the cycle ends having booted as many VMs as we could spread across all of our resources. With this method we should be able to increase the sleep time of main as it will be doing far more work per cycle and will likely have to wait a bit for VMs to register.

**Comment by crlb** [comment]
Commit bca28f5103e454a0877159125b59871fe51bea27 made many improvements, including round robin scheduling on groups. Within a group, we are still filling the clouds in priority order and do not attempt to spread the load across clouds.

**Comment by rseuster** [comment]
should we close ?

**Comment by rseuster** [comment]
closing
