### ISSUE TITLE
time line for condor when target alias is used

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#278]
Due to changes in the display of condor jobs on the web display, it is now possible to see
the different job categories not only by group but also by group and target_alias.

However, if that setting is used to display the jobs, and one wants to plot the timeline of jobs for a specific target_alias, e.g. idle jobs for belle/belle-local-worker or belle/None, then it still displays the idle jobs for the whole group.

It is not urgent, but it would be good to have those numbers plotted separately too.

**Comment by colsond** [comment]
Implemented in 2.9.1
