### ISSUE TITLE
count of slots/cores are wrong

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#279]
On csv2a (Version: stable-2.6.0 + 281 commits):
The count of VMs, total slots, busy and idle cores doesn't match and is also wrong.
Example in the attached screenshot:
On amazon-w for Belle there are 60  8core VMs which gives a total of 480 cores and runs only single core jobs.
The numbers displayed in csv2a are:
- 478 total slots
- 478 busy clores
- 47 idle cores 
Note: the idle cores count also goes up with time and the busy cores+ idle cores > 480.

Also in the expanded view, the counts are not correct - in this example 1_2 shows 63 slots used - with only 60 VMs.
![Screenshot_2020-01-06_07-37-58](https://user-images.githubusercontent.com/22002728/71828985-70720f80-3058-11ea-986b-75e2c7d3e39e.png)

**Comment by colsond** [comment]
After a quick audit of the database I think that the views are displaying the correct numbers as per the data in the database. I think the inaccuracies are coming from the fact csmachines doesn't do database deletes every cycle in an attempt to free up some computation. However with the other improvements that have been made to the machine poller I think we can go back to doing deletes every cycle. This should make the snapshots we are looking at in the web display more accurate on a per cycle basis. I've changed this configuration value on csv2a so hopefully this fixes this issue. If we are still seeing big discrepancies we can look at making code changes.

**Comment by colsond** [comment]
This problem should be fixed with the new amazon changes. csv2a may show a few extra slots until we take care of the 5 "rogue" VMs which are now showing up as foreign VMs.

**Comment by rseuster** [comment]
closing
