### ISSUE TITLE
Add graceful shutdown & pause functionality to csv2 processes 

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#283]
Currently when we shut down csv2 it simply kills the processes mid cycle which could potentially cause data loss or other issues.

We should add pause & stop configuration values for each process which will be checked at the end of each cycle. A pause will keep the process running in a permanent loop that waits for the pause flag to be cleared before continuing. The stop flag will cause a proccess to terminate at the end of the cycle; additionally, the ProcessMonitor class will also monitor this flag such that it doesn't restart the sub processes when they shut down and once all the children have gone away the service exits completely.

This should provide more data stability and the ability to run database utilities without fully shutting down all of the services.

**Comment by rseuster** [comment]
fully implemented ?

**Comment by colsond** [comment]
Yes this is in.
