### ISSUE TITLE
csv2-dev2 won't start VMs

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#288]
We have again jobs in the queue, but csv2-dev2 won't start new VMs. We have a shortfall in resources, but no available resources, according to cloudscheduler. However, the testing project on otter should have still slots free.

**Comment by colsond** [comment]
Seems like the views have stopped working, view_available_resources, and view_groups_of_idle_jobs are both currently empty. Investigating further...

**Comment by colsond** [comment]
This problem stemmed from 2 issues, firstly- the condor worker gsi process failed to insert the condor host id along side the certificate info; and secondly, the cloudscheduler.yaml config file was pointing to the wrong location for the certificate and key resulting in an "unreadable' status of the worker cert.

The first problem stopped the views from working properly and the second caused csv2 to think that the cloud would be unable to run jobs properly without a valid worker certificate. Both issues are now fixed on dev2 and VMs have started booting/running.
