### ISSUE TITLE
metadata: list priority, enabled flag and mimetype on webdisplay

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#291]
Would be nice if the webdisplay would show the metadata's metadata:
![image](https://user-images.githubusercontent.com/16807038/76645881-1c335200-6517-11ea-974d-7e7d0f86fb23.png)

similar to the cli:
```
$ cloudscheduler group metadata-list -g testing
Server: dev2, Active User: seuster, Active Group: testing, User's Groups: ['benchmarking', 'remote', 'test', 'test-dev2', 'testing']

Active Group/Metadata:
+---------+-----------------------------------+-------------+-------------+--------------+
+ Group   | Metadata Filename                 | Enabled     | Priority    | MIME Type    +
+---------+-----------------------------------+-------------+-------------+--------------+
| testing | accounting.yaml                   | 0           | 0           | cloud-config |
| testing | apel_accounting.yaml              | 1           | 1           | cloud-config |
| testing | benchmark.yaml                    | 1           | 0           | cloud-config |
| testing | cernvm-data.txt                   | 1           | 0           | cloud-config |
| testing | csv2htc.yaml.j2                   | 0           | -10         | cloud-config |
| testing | default.yaml.j2                   | 1           | 9           | cloud-config |
| testing | default_condorworker_cert.yaml.j2 | 1           | -1          | cloud-config |
| testing | docker_start.yaml                 | 1           | 10          | cloud-config |
| testing | jobnumber.yaml                    | 1           | 1           | cloud-config |
| testing | ssh-fix.yaml                      | 1           | 0           | cloud-config |
| testing | ssh_key.yaml                      | 0           | 0           | cloud-config |
+---------+-----------------------------------+-------------+-------------+--------------+
Rows: 11
```

**Comment by colsond** [comment]
Instead of adding data columns it would be easy to sort the metadata by their priority order and to color-code enabled/disabled metadata. IF you want to explicitly view the metadata's metadata it is available after you click on one.

**Comment by MCatherine1994** [comment]
hi @rseuster, we added the checksum for the metadata file and display it as the following. Instead of showing all metadata's metadata, we list them by the priority order, and use the grey color for the disabled ones. After clicking on a metadata name, the details will show which has a checksum value. Wondering how you like this design, any suggestion?
![Screenshot from 2021-09-09 10-34-53](https://user-images.githubusercontent.com/23131735/132735293-ab489848-d493-4c12-826f-97432c8344f6.png)

**Comment by MarcusEbert** [comment]
Is it possible to query the checksum with the cli for a specific yaml?

**Comment by MCatherine1994** [comment]
Query checksum from the cli could do something like this:
![Screenshot from 2021-09-09 14-13-55](https://user-images.githubusercontent.com/23131735/132763542-311c5daa-be72-426d-8ce9-9af6dbe369a2.png)

**Comment by MCatherine1994** [comment]
And if want to display the checksum next to the metadata file name, could do something like this, not sure how everyone likes it:
![Screenshot from 2021-09-09 14-14-35](https://user-images.githubusercontent.com/23131735/132763668-45841502-0788-4868-95cc-95cc037e682f.png)

with checksum label:
![Screenshot from 2021-09-09 14-18-26](https://user-images.githubusercontent.com/23131735/132764044-83dc1855-2288-44ee-94a1-0b4fdb56aa37.png)

**Comment by MarcusEbert** [comment]
I like the version in the first post much better; for the cli that sounds like what we need.

**Comment by colsond** [comment]
The latter ones could certainly be formatted better. I definitely like the look and feel of the first image but I think it will be nice to have the checksum available before clicking on an individual metadata file.

**Comment by MCatherine1994** [comment]
How about this one? And If click on the filename, the checksum here will be hidden, and it will show the normal metadata editor which has the checksum as well 
Metadata list page:
![Screenshot from 2021-09-10 10-13-21](https://user-images.githubusercontent.com/23131735/132892031-efa1cf47-fa56-44d1-b258-58343149dc30.png)

Click on a file name, show the metadata editor page:
![Screenshot from 2021-09-10 10-17-48](https://user-images.githubusercontent.com/23131735/132892474-135e8401-1c27-4102-a726-e1c4d7a3a6ff.png)

**Comment by MarcusEbert** [comment]
I still prefer the first one. I don't think we really need the checksum in the web display but only on the cli when trying to upload or check yaml files. For that, how the cli represents it that looks good and in the web display once you see the content should be fine too - that allows eas\y enough to check for changes compared to what one may have on the local computer.
