### ISSUE TITLE
overwrite group defaults with none

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#292]
On csv2a (stable-2.6.1):
For Belle-II there was a group default set for the VM keyname to be used. However, amazon does not has such key option. Selecting an empty key in the amazon cloud definition falls back to the group default. 
It would be good to have the option to select "none" which overwrites the set group default. Otherwise no group defaults can be used when a single cloud is enabled which doesn't support a specific option.

**Comment by colsond** [comment]
The main problem is you cannot override the group default with no-selection as the cloud level will default to the group level setting if the field is emptied. We need to provide a None option that overrides the group level selection.

**Comment by MCatherine1994** [comment]
Which fields do we like to have a "None" value to overwrite the group defaults? The group level defaults have: keyname, image, flavor, network and security  group. We could set keyname to be none, but I'm not sure if image, flavor and network could be none when we are trying to create vms? For security group, I saw it in the csv2_groups table, but our web interface doesn't have a place to set a group default security group, so not sure how we'd like to handle it.

**Comment by MarcusEbert** [comment]
* keyname
* flavor
* network
* security group

I think we could do it for all, but an image always needs to be selected. 
Depends also on what "None" does in the end. Will it select none for an option, or will it just ignore any settings and fall back to build in decisions (like for the flavor)?

**Comment by MCatherine1994** [comment]
This is what I did for the keyname as an example:
- select an empty option, does nothing, keyname in database is NULL, and will use the group default one when create vms
- select "None", sets the keyname to be "None" in database, this will ignore the group default, and won't provide any key when create vms
- select a normal keyname, provide whatever selected when created vms
![Screenshot from 2021-09-15 16-16-06](https://user-images.githubusercontent.com/23131735/133525179-6f31c4b6-96d7-49ce-862e-a397ccd73343.png)

When creating vms, we could ignore the keyname and the security group, but it will complain if there are multiple networks and we didn't specify which one. 
And I'm not sure if flavor also always needs to be selected.

**Comment by MCatherine1994** [comment]
What labels we'd like to show for the "use cloud or group defaults" and "ignore cloud and group defaults" options?
![Screenshot from 2021-09-20 12-53-46](https://user-images.githubusercontent.com/23131735/134066440-53c86ebd-491a-4b6b-8cbb-105ab4c69c60.png)
![Screenshot from 2021-09-20 12-54-08](https://user-images.githubusercontent.com/23131735/134066462-7f1f9dee-6f67-4a36-934c-6fb23173fe2d.png)

**Comment by MarcusEbert** [comment]
How about:
* "Use group default" instead of the empty field we currently have
* "Ignore group default" as new option; handle like there would be no default in the group and nothing selected in the cloud defaults

The best behaviour  that comes out of "Ignore group default" would be that cloudscheduler starts a VM in the same way like there would never been a group default set for that option; e.g. if we choose "Ignore group default" for the key then no key is provided in the startup, or if we choose "Ignore group default" for the flavor then csv2 tries to figure out the best flavor for the jobs itself (what it already does when there is no default set in cloud/group for flavor)
