### ISSUE TITLE
start VMs always with an alias for Condor

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#298]
We have the possibility to define an alias  and then add clouds to it. Jobs requiring an alias will result in VMs started on those clouds with the alias set for condor. 
In addition, jobs that do not require an alias can still run on those VMs. 

Example:  
Belle-II on csv2a defines alias for belle-local-worker with for example arbutus behind it.
This results in jobs that require belle-local-worker VMs to run only on those, and all jobs with no additional requirements will also run on those VMs.

Problem:  When there are jobs in the queue that do not have the belle-local-worker requirement, then VMs without this requirement will be started on arbutus. When then later jobs are in the queue with the belle-local-worker requirement then those jobs can not run on the VMs started on arbutus. This results in an unnecessary retirement of VMs.

Proposal: If a cloud is in exactly 1 alias present, then start VMs on this cloud always with this alias present in condor. 
This would allow all jobs suitable for a cloud to run on the same VMs.

**Comment by rseuster** [comment]
Not sure this would be the best and most general way. We might need to separate VMs based on things they provide: e.g. HasDocker or HasGPU.

For the problem at hand, why not define a second target_alias for all other VMs and change requirements for jobs:
Requirements = target_alias == "local"
for only local set of jobs and for the rest
Requirements = target_alias == "local" || target_alias == "everything_else"

Then have all VMs advertize either "local" or "everything_else".

**Comment by MarcusEbert** [comment]
The proposal is to start all the VMs with a specific alias on a cloud only IF a cloud is only in one alias. It is still possible to get different kind of jobs for the same alias which would require a different VM, in which case a VM would get retired to provide a new one which has the correct requirements. However the proposal would allow to run jobs that have exactly the same machine requirements in the same VM if the only difference is their target_alias requirement (some have it, some have none).

Changing the Requirement string in a job requires changes on the experiment system, while a change in csv2 behavior is independent of any experiment and a more general way. But it could be a temporary fix of the problem.

**Comment by rseuster** [comment]
closing
