### ISSUE TITLE
EC2 list image 

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#307]
csv2a, stable-2.7:

Trying to list images on EC2 shows different errors about architecture or user. After filling out the fields on the top it complained about, it gives:
Error: EC2-00066 cannot switch to invalid group "".

instead of listing the images. Images asked for are for self, shared, and amazon

**Comment by colsond** [comment]
Are you trying to list ec2 images via command line? the manpages explicitly say it only works for openstack clouds.

If you give me the command you were using I'll see if I can clean up the error handling.

**Comment by MarcusEbert** [comment]
No, it is on the web interface. (belle2 group)

**Comment by colsond** [comment]
Ah i see i missed the csv2a part, ill investigate.

**Comment by colsond** [comment]
Closed until EC2 in use again.
