### ISSUE TITLE
have csv2 send warnng emails if disk or memory gets close to full

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#308]
we had a disk fill up today, resulting in job and vm losses.

since csv2 already monitors the CPU, disk, swap and memory, have it also send warning emails if either becomes critical.

Also, we have a second disk configured, but not used. So, a clean solution would be to mount at boot time
the second, big disk under /var/log -> change in ansible and / or cobbler required

**Comment by colsond** [comment]
Sysadmin issue not csv2 issue.
