### ISSUE TITLE
chameleon: cannot change any cloud settings due to unknown volume_type in webgui

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#309]
chameleon is setup a bit differently such that one needs to give a "volume_type" when creating a volume.

Try change any item in this page:
https://csv2a.heprc.uvic.ca/cloud/list/?atlas-uvic#chameleon

It will fail claiming it doesn't know the volume_type.

commandline works file.

**Comment by colsond** [comment]
This is a one line fix for the validation of that field in cloud_views. csv2 simply did not know how to validate the field so it rejected it.
