### ISSUE TITLE
Keep information from failed attempts to create new users or clouds

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#314]
Filling out the information about a new cloud results sometimes in errors since it is not always clear what to put in (lower case usage is not clear to users, Default vs default usage  in domain names is not always clear, password may be typed wrongly,...).
The behavior in the latest version is that:
* an error pops up only a few seconds on the bottom of the screen; time is too short to even read it
* all fields are cleared in case of error and one has to start over from scratch

proposed new behaviour:
* keep the errors on this page without a time limit; it will be removed at the next submission or when changing the page anyway
* keep all fields filled with the previous content so one can just change a single field instead of filling out everything from scratch

**Comment by colsond** [comment]
TIme limit on errors has been removed.
Form data retention added to roadmap.

**Comment by MCatherine1994** [comment]
Handle error message:
- [x] successfully message timeout after 5s 
- [x] error message stays but will be removed when click anywhere else on the page

Retain form data:
- [x] let add method in cloud_views return fields data in error cases
- [x] let cloud_list method in cloud_views format and render a cloud_add data to clouds page (data either from last try or use default values)
- [x] let clouds page, cloud add section read cloud_add data
- [x] stay on add cloud page in error case
