### ISSUE TITLE
Cloud priority not represented in boot proccess

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#315]
Once the scheduler has chosen a cloud to boot on it sets the cloud priority level then tries to boot only on clouds of that priority level. However, in choosing that first cloud cloud priority does not seem to be a concern.

For each group we find the highest priority job that needs a VM
From that job row in the view groups_of_idle_jobs it retrieves the best fit flavors or the flavor requested in the job.
Then from those flavors it retrieves the relevent cloud and tries to boot on the first match.

This last step should get all the clouds associated with the flavors listed for the job and then the highest priority one should be chosen instead of the first one found.

**Comment by colsond** [comment]
Double check that the view sorts flavors in cloud-priority order.

**Comment by MCatherine1994** [comment]
The cloud:flavor pair listed in the "flavors" column in the "view_groups_of_idle_jobs" table doesn't sort by the cloud priority order, update this view to let the "flavors" column ordered by priority should solve this problem.
