### ISSUE TITLE
Adding Cloud Metadata With an Invalid Name Causes the Webpage Redirect to Occur Within a Box

### ISSUE THREAD

**Issue by michaelklassen02** [hep-gc/cloudscheduler#319]
When adding metadata to an individual cloud via the Metadata tab on the Clouds page, if the metadata fails to be added, the page redirect will occur within a box:
![Screenshot from 2021-02-12 13-30-44](https://user-images.githubusercontent.com/64805118/107825286-aee7fc80-6d37-11eb-94b8-b6e8364ba60a.png)
The inside page functions as normal, and will vanish on refresh.

**Comment by MCatherine1994** [comment]
Need to check the metadata related method in cloud_views.py, for example the [metadata add method](https://github.com/hep-gc/cloudscheduler/blob/4c77ca9edcd61e9273aade20420f27dba5d95c6d/web_frontend/cloudscheduler/csv2/cloud_views.py#L840), almost in all the error cases, it returns the cloud_list page, which results in the above issue, the whole cloud page be re-rendered in the iframe section. It should return and render the meta_editor content in that section

**Comment by MCatherine1994** [comment]
![image](https://user-images.githubusercontent.com/23131735/127373680-09c68b0b-b191-4bc0-b631-bd64666da6e4.png)
In the error cases, updated to show an empty page with the error message, it now works in the same way as the group metadata page under "Defaults" tab
We could review this to see if want this empty page or better still return the editor
