### ISSUE TITLE
Field Too Long Errors Display as Standard Messages

### ISSUE THREAD

**Issue by michaelklassen02** [hep-gc/cloudscheduler#321]
When typing a data field on the web frontend, if the input is too long for the database but obeys all other restrictions of the field, the failure message will come back as a standard (not bolded) message instead of the usual bolded error message.
![Screenshot from 2021-02-22 14-58-54](https://user-images.githubusercontent.com/64805118/108781623-09930c80-751f-11eb-9a48-5bf6c119f8c1.png)
This doesn't appear to affect any of the functionality (the objects do not appear to be added, etc).

**Comment by michaelklassen02** [comment]
The reverse of this error (a standard message appearing bolded like an error) occurs for uploading images

**Comment by MCatherine1994** [comment]
- [x] The defaults function in [web_frontend/cloudscheduler/csv2/group_views.py](https://github.com/hep-gc/cloudscheduler/blob/9da17022a5243d9d37b9bf11854156a003a0b4c1/web_frontend/cloudscheduler/csv2/group_views.py#L269) handles the group defaults page. Use the rc variable value (0 or 1) to decide if there is an error or not. In the above case, rc should be 1, but its value has been overwritten by other db operations, so we should avoid this kind of overwrite.
- [x] Images and upload images pages set footer message to use bold at all time, while other pages only set footer to use bold when there is an error message. For internal consistent, update image, upload image pages to not use bold for normal message
- [x] In upload image method, some of the error cases doesn't set the rc (response code) to 1, so the error message is shown as normal
