### ISSUE TITLE
create and display MD5 checksum for yaml files

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#322]
it would be nice if csv2 would show a checksum on its page:
![Screenshot_20210303_091615](https://user-images.githubusercontent.com/16807038/109845693-45566200-7c02-11eb-9484-ff4160e35711.png)

my workflow of modifying yaml files is to checkout cloud-configs from github, modify the file in question, then upload into csv2
and last do a backup of all yaml files from csv2 back into github (backups are here https://github.com/hep-gc/cloud-configs/tree/master/csv2). Without a checksum, I cannot easily identify if someone else modified the file recently. Previous changes might be lost.

**Comment by MCatherine1994** [comment]
refs commit [2dacfe4](https://github.com/hep-gc/cloudscheduler/commit/2dacfe49922c62351175f239402e0956d1ad3b1b), [
9877b6e](https://github.com/hep-gc/cloudscheduler/commit/9877b6e56d6e317b1de16f83f89379912a6deb21)
