### ISSUE TITLE
link to github from csv2 web page

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#323]
How are other users supposed to submit bug reports about csv2 ?
The csv2 web pages should contain a link to github. The users can then follow this link and submit their bug reports

**Comment by MCatherine1994** [comment]
- [ ] add a button to top navbar to link to the reporting bugs/submitting issues page
- [ ] add a button to top navbar for condor installation or other installation support
- [ ] add link to the github repo at the right bottom of the page, maybe around the version text

if feel like there are too much buttons in the navbar, could also have a new button called "Tools", and make the submit issue and installation support as the dropdown options

**Comment by MCatherine1994** [comment]
hi @MarcusEbert, @colsond, how do we like the design to place the two extra buttons on the nav bar?

1. Have a dropdown menu in the nav bar which has the two options "Condor Installation" and "Report Issue":
On large screen:
![Screenshot from 2021-09-14 15-43-37](https://user-images.githubusercontent.com/23131735/133343544-ab812ebe-299a-4af1-a20f-8bc964895285.png)

On smaller screen:
![Screenshot from 2021-09-14 15-50-19](https://user-images.githubusercontent.com/23131735/133344096-bbc4e331-83b9-4f17-b272-1a89ed74b4ba.png)


2. Place them directly on the nav bar:
On large screen:
![Screenshot from 2021-09-14 15-48-39](https://user-images.githubusercontent.com/23131735/133344130-3133f4df-b450-428b-a1fa-3bf6effd4a00.png)

On smaller screen:
![Screenshot from 2021-09-14 15-48-58](https://user-images.githubusercontent.com/23131735/133344141-f8d8e8d5-c4a8-41b9-a2b4-a157ed4dfa07.png)

**Comment by MarcusEbert** [comment]
How about:
* add on the top instead of "Tools" just "HTCondor plugin"  (or similar, it is not really an installation of condor)
* on the bottom where it says "Versions: stable-2.9.1+5 commits" , add under it "Report issues" which then redirects to github and the correct branch?

**Comment by MCatherine1994** [comment]
Okay, got the nav bar updated to have the "HTCondor plugin", and place the report issue to the right bottom, "version" is linked to the csv2 github latest tag page, "report issue" is linked to the csv2 github issue page. Do we want the user click the link and open the page in the current tab, or in a new tab?

![Screenshot from 2021-09-15 10-45-19](https://user-images.githubusercontent.com/23131735/133483303-703bf375-5a37-4500-ad29-cf15152aab85.png)

**Comment by MarcusEbert** [comment]
I like this new version. I think it would be good to open a new tab for github or issue reporting.
