### ISSUE TITLE
Header Bar Covers Important Buttons In Half-Width Screen

### ISSUE THREAD

**Issue by michaelklassen02** [hep-gc/cloudscheduler#325]
When the screen is skinny enough that the header bar splits into two rows, some buttons are inaccessible:
![test_web_key_delete_screenshot](https://user-images.githubusercontent.com/64805118/112677115-8a973980-8e26-11eb-8cae-14716db2464e.png)
This is confirmed to be an issue on the key page. Which other pages it shows up on will require additional investigation.

**Comment by MCatherine1994** [comment]
- [x] Keys section missing right nav options:
right nav bar ["users", "groups", and "config"](https://github.com/hep-gc/cloudscheduler/blob/8d4884b512fb96c800288f796629f3cd30dc653d/web_frontend/cloudscheduler/csv2/templates/csv2/navigation_bar.html#L39) only show to super users, but the keys page doesn't render with the super user info, could check in the [keypair_view](https://github.com/hep-gc/cloudscheduler/blob/8d4884b512fb96c800288f796629f3cd30dc653d/web_frontend/cloudscheduler/glintwebui/keypair_views.py#L56) file; other pages like status.html and image.html all have the "is_superuser" attribute, could see an example in [cloud_view](https://github.com/hep-gc/cloudscheduler/blob/8d4884b512fb96c800288f796629f3cd30dc653d/web_frontend/cloudscheduler/csv2/cloud_views.py#L1630). so added this "is_superuser" attribute should make it work as expected

- [x] on small screen, nav bar overlaps the page content, hide the important buttons
for each web page, like status.html or manage_keys.html, the page content is either padding top a fixed value or hardcode a top value, to leave the space for top navbar. When the window size gets small, the navbar height increase, it will then overlap with the page content. An idea is to adjust the padding-top or top value based on the window size
