### ISSUE TITLE
GSI and python bindings - keep an eye on ticket

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#33]
python bindings installed via pip don't work with GSI. python2 bindings via RPM installs do work.

This is the ticket.
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6692

Hope the next version (released hopefully soon) will have it fixed.
BTW - python bindings should be backwards compatible, so bindings for 8.7.X should work well with our version 8.6.9.

**Comment by colsond** [comment]
The new bindings seem to work fine and we are no longer using the version 2 bindings at all. The ticket has also been resolved and they (htcondor developers) have improved their packaging process.
