### ISSUE TITLE
adding mark messages into the condor_poller log

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#334]
We had multiple times the issue that the condor_poller, or specific threads of it, stop doing anything while the condor poller itself still runs. 

To easier identify such issues, it would be helpful to have regular marking messages in the log, e.g.
------ POLLER THREAD NAME ------

If such message appears every x min (let's say 10min), then we can see with an easy grep if a thread is still alive and if not can have some automated reaction, e.g. restart of the condor poller.

**Comment by MCatherine1994** [comment]
refs commit: #[435dfaa](https://github.com/hep-gc/cloudscheduler/commit/435dfaa174abefff9c0db41fb8f5bbed135b78f4)
