### ISSUE TITLE
Update unit test row check tests

### ISSUE THREAD

**Issue by MCatherine1994** [hep-gc/cloudscheduler#335]
Some unit test file need to update its row check tests:

cloud_update #47, #49:
![image](https://user-images.githubusercontent.com/23131735/131724803-0bbc7ef0-815b-4599-a565-e584dc02a094.png)

cli_defaults #14, #17, #20:
![image](https://user-images.githubusercontent.com/23131735/131725696-b5ecb3f3-180f-4ece-816a-0ff336a8fcf4.png)
0017 (0017) test_cli_defaults Failed: expected_rc=0, expected_modid=None, expected_text=None, cmd=cloudscheduler defaults list -NV -su dmeng-clu3 -s unit-test -spw b8wm5iK3nW
	return code=0
	module ID=None
	stdout=
![image](https://user-images.githubusercontent.com/23131735/131725840-b81ebbd1-6157-4fcd-912f-010c2f482a4a.png)
0020 (0020) test_cli_defaults Failed: expected_rc=0, expected_modid=None, expected_text=None, cmd=cloudscheduler defaults list -V '' -su dmeng-clu3 -s unit-test -spw b8wm5iK3nW
	return code=0
	module ID=None
	stdout=
![image](https://user-images.githubusercontent.com/23131735/131725858-fb936c22-0e01-4256-94f2-75cf1c5d06b4.png)

cloud_status #7:
0007 (0007) test_cloud_status Row Check: request='/cloud/status/', group=dmeng-ctg1, expected_list='cloud_status_list', list_filter={'group_name': 'dmeng-ctg1', 'cloud_name': 'dmeng-ctc2'}
	1 rows were accepted by the filter.
	Row 1:
		Actual values in response: {'group_name': 'dmeng-ctg1', 'cloud_name': 'dmeng-ctc2', 'app_credentials_expiry': None, 'VMs': '0', 'VMs_manual': '0', 'VMs_in_error': '0', 'VMs_starting': '0', 'VMs_retiring': '0', 'VMs_unregistered': '0', 'VMs_idle': '0', 'VMs_running': '0', 'cores_native': '0', 'ram_native': 0.0, 'slot_count': '0', 'slot_core_count': '0', 'slot_idle_core_count': '0', 'Foreign_VMs': '17', 'enabled': 1, 'communication_up': 1, 'communication_rt': 559, 'cores_ctl': -1, 'cores_limit': 300, 'VMs_quota': 70, 'VMs_native_foreign': '17', 'cores_quota': 300, 'cores_soft_quota': -1, 'cores_foreign': '88', 'cores_native_foreign': '88', 'ram_ctl': -1, 'ram_limit': 614430, 'ram_quota': 614430, 'ram_foreign': 197632.0, 'ram_native_foreign': 197632.0, 'volume_gigs_max': 0, 'volume_gigs_used': 0, 'tag': '', 'display': 1}
		For the key cores_foreign: expected 0, but got 88.
		For the key cores_native_foreign: expected 0, but got 88.
		For the key ram_foreign: expected 0, but got 197632.0.
		For the key ram_native_foreign: expected 0, but got 197632.0.

**Comment by HeroHFM** [comment]
Updated in stable-2.10.3b (ac1f7935848c96fa782f48cb45d3aa906914008b).
