### ISSUE TITLE
Rename the "Defaults" tab

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#342]
Defaults is a bit of a misnomer as there are default options on several of the tabs. The "Defaults" tab is actually the "Group level defaults" so we should try to think of a better name that better describes the tab.

**Comment by MCatherine1994** [comment]
Rename navigation bar options:
- cloud -> cloud config
- defaults -> group config
- config -> system config

Rename empty option for cloud/group config fields:
- cloud config page, image field, rename empty to "use group default"
 - group config page, all fields, rename empty to "auto detect"
