### ISSUE TITLE
Make the services and system resources admin only

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#343]
General users don't need to see those metrics as they would need an admin to fix any relevant issues anyways, we should hide them for non super-users to free up more screen real-estate.

**Comment by MCatherine1994** [comment]
Updated for normal user, won't show system services/resources metrics
![Screenshot from 2021-11-16 09-40-33](https://user-images.githubusercontent.com/23131735/142037896-a09f07dc-77c7-4dc0-88a1-a28a8cf86aef.png)
