### ISSUE TITLE
Flush openstack// FVM data on certain cloud updates

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#344]
It's possible to change a registered cloud significantly by changing the user, tenant or other such options. This case comes with some notable issues:
1) if there are any csv2 vms running in the previous tenant/project (before it was udpated) csv2 will lose track of them (either don't let them update or terminate vms?)
2) the foreign VM accounting will change so the old FVM table data should be removed
3) the openstack metadata (flavours/images/etc) can be quite different between groups so the old one should be removed when an update of this type goes thru

**Comment by MCatherine1994** [comment]
If any of "authurl", "username", "project", "region", "userid" changed, want to clean the openstack/fvm data table:
image, flavor, network, key, security group, volume, limit, vm, foreign vm?
