### ISSUE TITLE
Update scheduling view to use reported ram and CPU values

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#346]
RIght one the view we use in scheduling calculates the number of available slots/cores/ram by summing up our usage along side the foreign VM usage. This is an error prone way of getting these metrics since old VMs can have flavors that have been changed or no longer exist which can effect the accounting. The limit poller gets the usage values directly from the cloud which should be more accurate.

**Comment by MCatherine1994** [comment]
need to review how we use the disk info when boot vms

**Comment by MCatherine1994** [comment]
refs: [6799c2f](https://github.com/hep-gc/cloudscheduler/commit/6799c2fc714877db052cfb57ca56b22826da6677)
