### ISSUE TITLE
update condor poller installation process

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#348]
This process can be boiled down into a script and Victor has already written a prototype that needs to be tested.

The idea here is it takes all the steps that are listed at the /repo/ url and puts them in a bash script. The script also backs up their old config value and asks the user if they want to use the condor key and cert locations specified in the old config file before writing out the new one. Here is the script prototype:

`#!/usr/bin/env bash

OLD_CFG=/opt/cloudscheduler/etc/cloudscheduler/condor_poller.yaml
NEW_CFG=/tmp/cloudscheduler/etc/cloudscheduler/condor_poller.yaml

cd /tmp
wget https://csv2.heprc.uvic.ca/repo/condor_poller.tar.gz
tar -xzvf /tmp/condor_poller.tar.gz

if [ -f "$OLD_CFG" ]; then

    cp $OLD_CFG "$OLD_CFG.old"

    OLD_CERT=$(sed -n 's/\s*condor_worker_cert: //p' $OLD_CFG)
    NEW_CERT=$(sed -n 's/\s*condor_worker_cert: //p' $NEW_CFG)

    if [ ! -z "$OLD_CERT" -a "$OLD_CERT" != "$NEW_CERT" ] ; then
        read -p "Keep previous certificate location ($OLD_CERT) (y/n)? " choice
        case "$choice" in 
          y|Y ) sed -i "s#$NEW_CERT#$OLD_CERT#g" $NEW_CFG;;
        esac
    fi

    OLD_KEY=$(sed -n 's/\s*condor_worker_key: //p' $OLD_CFG)
    NEW_KEY=$(sed -n 's/\s*condor_worker_key: //p' $NEW_CFG)

    if [ ! -z "$OLD_KEY" -a "$OLD_KEY" != "$NEW_KEY" ] ; then
        read -p "Keep previous key location ($OLD_KEY) (y/n)? " choice
        case "$choice" in 
          y|Y ) sed -i "s#$NEW_KEY#$OLD_KEY#g" $NEW_CFG;;
        esac
    fi
fi

rsync -av /tmp/cloudscheduler /opt`

**Comment by HeroHFM** [comment]
Implemented in stable-2.10.3b (ac1f7935848c96fa782f48cb45d3aa906914008b).
