### ISSUE TITLE
unable to add cloud to alias

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#357]
```
cloudscheduler alias add -g atlas-cern -an lrz-lmu_cloud -cn lrz-pe72te
Error: AV-00169 cloud alias add, value specified for "alias_name" must be all lowercase letters, digits, dashes, underscores, periods, and colons, and cannot contain more than one consecutive dash or start or end with a dash.
```
to me, the cloud name looks ok to me, cloudscheduler insists otherwise.

**Comment by rseuster** [comment]
this is a little bit urgent, as we have a dedicated 80 core node on LRZ, that's sitting idle now. Could be great to resolve this.

**Comment by MarcusEbert** [comment]
worked to created it from the web interface.

EDIT: NO it did not; created a new alias instead.

**Comment by colsond** [comment]
This was fixed when updating the field validation functions in the web interface.
