### ISSUE TITLE
Create a public status page

### ISSUE THREAD

**Issue by MCatherine1994** [hep-gc/cloudscheduler#373]
Requirement:  
- open to public, no need to login
- hide the navigation bar and the bottom system service metrics
- hide the job table
- hide the vm detail overlay
- allow group owner to config if want to show the group to public
- refresh the page in a certain amount of time

Ideas:  
- Use [wget](https://www.guyrutenberg.com/2014/05/02/make-offline-mirror-of-a-site-using-wget/) to save our web page as a static html, by providing username/password to the url like `wget --convert-links --adjust-extension --page-requisites --no-parent https://[username]:[password]@csv2-dev.heprc.uvic.ca/`
- Could create a specfic user, use this user's credential to do the wget, and when want to show a group to public, just add this user to that group
- Need to think of how to host this public page, maybe the same way as the condor install repo page, check the apach config `ls /etc/httpd/conf.d` and `/etc/httpd/conf.d/csv2_ssl.conf`

**Comment by HeroHFM** [comment]
Implemented in stable-2.10.3b (ac1f7935848c96fa782f48cb45d3aa906914008b).
