### ISSUE TITLE
Query clouds for supported volume types

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#377]
Presently we can use Volumes in csv2 by specifying several pieces of configuration in a short yaml file as follows:

`{"GBs": 10, "GBs_per_core": 10, "volume_type": "volumes-ssd" }`

However, the volume_types supported are specific to a given cloud and are defined on their end. To make things more usable for csv2 users we should find out if we can query the list of volume types from the cloud and have them available as a dropdown like the rest of cloud configuration instead of forcing users to either already know what the cloud supports or just guessing and trying some common ones.

**Comment by HeroHFM** [comment]
Implemented in stable-2.10.3b (ac1f7935848c96fa782f48cb45d3aa906914008b).
