### ISSUE TITLE
ERROR in /var/log/cloudscheduler/cscollector.log

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#38]
```
2018-05-31 13:19:37,936 - Machine Poller - ERROR - Error constructing machine dictionary for 
    [
        Activity = "Idle"; 
        TargetType = "Job"; 
        Machine = "atlas--cc-west-a--90438801284829.westcloud"; 
        EnteredCurrentState = 1527534627; 
        group_name = "atlas"; 
        MyType = "Machine"; 
        Name = "slot1@atlas--cc-west-a--90438801284829.westcloud"; 
        MyCurrentTime = 1527797447; 
        TotalSlots = 1; 
        State = "Unclaimed"; 
        SlotType = "Partitionable"; 
        MyAddress = "<10.39.18.16:9618?CCBID=206.12.154.228:9618%3faddrs%3d206.12.154.228-9618+[2607-f8f0-c10-70f3-2--228]-9618%26noUDP%26sock%3dcollector#13&PrivNet=atlas--cc-west-a--90438801284829.westcloud&addrs=10.39.18.16-9618+[--1]-9618&noUDP&sock=3550_e5b4_3>"; 
        Start = ( Owner == "seuster" ); 
        flavor = "atlas:cc-west-a:c2-7.5gb-31"
    ] continuing with next resource.
2018-05-31 13:19:37,937 - Machine Poller - ERROR - KeyErrortype error occured
2018-05-31 13:19:37,937 - Machine Poller - ERROR - 'flavor'
```

**Comment by colsond** [comment]
The entry for flavor was missing from the csv2_attribute mapper, I've added a table entry for it and restarted the machine poller. I'll look at some options to make sure this wont crash the poller- some preliminary ideas:
- if extra attributes are found check if they exist in the automapped machine object and add them regardless of the attribute mapper (update attribute mapper to return a list of unmapped attributes)
- simply throw out non-mapped variables which would stop the crashes but may insert incomplete machine classad entries into the database

**Comment by colsond** [comment]
Updated in commit 36e8a47964b98693f700b3dcb1bed984cd456cc1- the attribute mapper now returns a list of unmapped attributes which are then reported in the poller logs.
