### ISSUE TITLE
Keep selected group when updating User settings

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#400]
on csv2.heprc (V2.11.0) the active group is changed when user settings get updated.

To replciate:
- select a group as active which is not your default group (e.g. BaBar on csv2.heprc, with Belle be the default group)
- go to "User Settings"
- click "Update User"

Result:  Active group is changed from "BaBar" to "Belle"
expected result: Active group stays as "BaBar"

**Comment by alyssa-blair** [comment]
Fixed in #403. User Settings and other pages with similar issues now maintain the active group upon configuration.
