### ISSUE TITLE
Handling Problems with the Cloud Controller

### ISSUE THREAD

**Issue by berghaus** [hep-gc/cloudscheduler#5]
Many times in the past the Nova interface of the CERN OpenStack has become unresponsive, for example for scheduled updates.  In those instances, the worker nodes are still registered on condor, responsive, and running jobs. Our usual strategy is to disable cloud scheduler while this maintenance is going on because it will kill VMs after not being able to check on them for a while (is this still true?).

Is it possible to stay the delete commands until the instance had also been removed from the condor pool? This would slow down the deletion of erroneous instances because it takes a while for an unresponsive worker node to disappear from the condor pool, but it would make the system more stable from the user perspective, that is jobs will be less likely to fail.

**Comment by colsond** [comment]
come back to it later

**Comment by rseuster** [comment]
closing
