### ISSUE TITLE
add a keep alive time to vm

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloudscheduler#53]
Support a Keep Alive time / setting so VMs aren't retired so quickly

**Comment by crlb** [comment]
1. vm_keep_alive is an integer and specifies the number of seconds to retain an idle VM. 
2. vm_keep_alive has been added to csv2_group_defaults (for group wide specification), default Null, and can be overridden at the csv2_group_resource (cloud) level.
3. vm_keep_alive has been added to csv2_group_resource, default Null.
4. vm_keep_alive has been added to view_group_resources and is determined by the value specified at the cloud level, then the group level, or zero (0).
5. vm_keep_alive has been added to view available resources and is copied from view_group_resources.
6. keep_alive has been added to csv2_vms, is derived from vm_keep_alive (see #5)  and is maintained and used by the scheduler.

**Comment by crlb** [comment]
fixed 107bc283eba78ee9f80bdb00b91ca4890579b1a6
