### ISSUE TITLE
add group metadata exceptions

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloudscheduler#57]
metadata can be provided at both the group and the cloud level. For any particular cloud, all enabled metadata is collated and passed to new VMs on the cloud. The purpose of this capability is to allow the definition of group wide metadata but allow selected files to be bypassed (disabled)  for one or more clouds.

**Comment by crlb** [comment]
Table "csv2_group_resource_metadata_exceptions" created with three columns: group_name, cloud_name, and metadata_name. 

"view_metadata_collation" lists the metadata files to be collated for each cloud in priority order. It provides: group_name, cloud_name, metadata_name, priority (positive/negative integer, lowest value is highest priority), and type ("group" - csv2_group_metadata, or "cloud" - csv2_group_resource_metadata). This view does not list metadata files that have been disabled, or group metadata files that have been excluded by match csv2_group_resource_metadata_exceptions records.

**Comment by crlb** [comment]
csv2_group_resource_metadata_exceptions renames to csv2_group_metadata_exclusions

**Comment by colsond** [comment]
It seems this table was added in commit 61271bf50af2a5a191a8688b1282fafee3f0991a, is this functionality now fully implemented?

**Comment by mhpx** [comment]
Still pending.
The views were changed again recently and it's not yet in the scheduling code to use them.

**Comment by crlb** [comment]
Implemented 6ae69786668e660da784416537e33b31b0e9d277 - but  nomenclature is "group metadata exclusions".
