### ISSUE TITLE
flavor veto / exclude option

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloudscheduler#62]
Need ability to disable certain flavors from being selected.

**Comment by crlb** [comment]
cli and server support implemented. Web and scheduling (view_available_resources) support outstanding.

**Comment by crlb** [comment]
Commit 8ecb0132ab8a34e74ebba201ed6695441b65b5e7 added support in view_available_resources which also cascades to view_groups_of_idle_jobs.

**Comment by kcasteels** [comment]
Exclusions added and tested on frontend.
