### ISSUE TITLE
sort yaml files in cloudscheduler group list according to priority

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#63]
it would be nice if the
```
cloudscheduler group list
```
would give the yaml files in the same order than later transfered and executed on the VMs.

**Comment by crlb** [comment]
use “cloud scheduler cloud metadata-collate”

**Comment by rseuster** [comment]
What is this command supposed to do ?
```
[seuster@csv2 ~]$ cloudscheduler cloud metadata-collate
Error: Invalid action "metadata-collate" for object "cloud"; use -h or -H for help.
```
Why a separate command ? Why not just order the list ? Possibly also either an option to
```
cloudscheduler group metadata-list
```
to print either in alphabetical or in order of execution on the VM.

**Comment by crlb** [comment]
the command is  “cloud scheduler cloud metadata-collation". This command takes account of the metadata cascading from the group metadata and not just the metadata associated with a particular cloud.
