### ISSUE TITLE
Bug or feature: do we want to separate VMs from different owners in CSV2 ?

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#64]
I am testing cvs2 by submitting jobs as a different user / owner in csv2 than the official production jobs, which are submitted as "autopyfactory". I am increasing the jobs, now there's constantly some jobs idle, but csv2 doesn't boot new VMs because slots on VMs booted for the autopyfactory are still available.

Before implementing any changes, we need to decide if this is a bug or feature.

Currently, when a VM is booted, we have a start expression that lets only jobs from a single user (or owner in condor speak) run on that VM. This is inherited from version 1. In csv2 we also separate on groups. Does this make the owner separation obsolete ?

Pro separating owners: 
- with different owners, abuse hits only the same owner. This way we could separate different panda queues for example. Some jobs might take over whole machines or excessive memory and affect production jobs. Could be mitigated by using cgroups or booting VMs that fully match job's requirements (at the moment I boot 8 core VMs also for single core jobs, which then creates 8 slots)
- if we ever use containers for running workloads, it becomes super-cheap to retire and boot new workers for different users
- can use fair chair of owners in condor (would probably be more fine grained when owners are not separated though)

Contra separating owners:
- with groups in csv2 not needed any more, we could create different groups for different panda queues in above example
- would probably make csv2 code easier than with separation
- some other institutes that will use csv2 might have lots of uses and small number of groups. They might not want to separate VMs from different owners

Comments ?

**Comment by crlb** [comment]
Hi Rolf,
   I would like to discuss this when I return; I don’t fully understand everything in your email.
   The intent was to be like OpenStack, where everything is done on behalf of the project (group); ie. it shouldn’t matter who submits work to the group, jobs should belong to the group, but I don’t understand all your pros and cons so I can’t make the argument here. So we need to talk.

Colin..

**Comment by colsond** [comment]
Can this issue be closed? I think it is now clear that we are going with a group centric approach but I'm not sure if the vm job start expression issue was resolved?

**Comment by mhpx** [comment]
The temp fix is just to edit the Start expression in the default yaml to remove the Owner check. Since groups can control their yaml they can tweak that behavior as desired down the road since CS can still provide the template variable to use however they see fit.

**Comment by colsond** [comment]
user would need change the start expression.
Won't fix
