### ISSUE TITLE
Logoff button needed

### ISSUE THREAD

**Issue by kcasteels** [hep-gc/cloudscheduler#72]

**Comment by colsond** [comment]
just tested. doesn't really work. reopening the page doesn't require password.
Do we need a "login" button ?

**Comment by colsond** [comment]
To get this working will require some more changes to the apache config. This doc has all the information we'll need:

https://httpd.apache.org/docs/trunk/mod/mod_authz_dbd.html

Typically how this is done is via a "login portal" where you have one page available to all users without authentication and use that page to login and set the user's login status. Then conversely you have a logout page that requires login to get to but unsets your login status.

Login:
`  <Files "login.html">
    # don't require user to already be logged in!
    AuthDBDUserPWQuery "SELECT password FROM authn WHERE user = %s"

    # dbd-login action executes a statement to log user in
    Require dbd-login
    AuthzDBDQuery "UPDATE authn SET login = 'true' WHERE user = %s"

    # return user to referring page (if any) after
    # successful login
    AuthzDBDLoginToReferer On
  </Files>
`

Logout:
`
  <Files "logout.html">
    # dbd-logout action executes a statement to log user out
    Require dbd-logout
    AuthzDBDQuery "UPDATE authn SET login = 'false' WHERE user = %s"
  </Files>
`

**Comment by rseuster** [comment]
doesn't work on production. Would be good to have this for the next merge

**Comment by kcasteels** [comment]
Logoff button now works using jquery. Ewwwww. I'm going to change it to use vanilla javascript.... But it does work.

**Comment by kcasteels** [comment]
The logoff is now working with vanilla JS. No jquery! Closing...
