### ISSUE TITLE
docker swarm V kubernetes

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#73]
I know we have designs to "containerize" csv2 for ease of deployment and since it is a distributed system we will probably want to look into a container orchestration platform such as docker swarm or kubernetes. I will update this issue with more information as I learn about the technologies.

At first glance kubernetes looks like the industry standard and most commercial clouds support it (openstack does too). However, if in the future we are looking to containerize the job applications running Docker swarm has the merits of being tightly coupled to the docker api and is probably faster to spin up than a kubernetes node.

**Comment by rseuster** [comment]
Matthew worked on kubernetes
