### ISSUE TITLE
rename entries in database : csv2_group_resources and csv2_group_resources_metadata

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#77]
replace the "resources" with something containing "cloud".
E.g. "csv2_group_cloud_configuration" would be fine with me. Or
"csv2_group_cloud_settings" to reflect how it's called on the web display.

**Comment by colsond** [comment]
aim for next merge

**Comment by mhpx** [comment]
@kcasteels is anything in the web frontend affected by this change to the tables?
csv2_group_resources - > csv2_clouds
and 
view_group_resources_with_metadata_info - >  view_clouds_with_metadata_info

**Comment by crlb** [comment]
done, f5cab781645ccba738376eba0f9625facfe3e457
