### ISSUE TITLE
bug when retire VMs

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#79]
Reproduce issue:   
- go to csv2 status page
- click on cloud name under "Clouds"
   - it then shows all the VMs on that cloud
- select some VMs 
- click retire to retire the selected VMs

Issue:
 - after csv2 finished to change the status to "retiring" it does NOT go back to show the **VMs on the select cloud** but shows the VMs from all clouds

expected behaviour:
 - show again only the VMs on the selected cloud

**Comment by colsond** [comment]
update ?

**Comment by kcasteels** [comment]
Both VM retire and kill where broken due to database and code changes. Both are now working again, with further web UI colour coding enhancements.

**Comment by kcasteels** [comment]
This can be tested on csv2-dev.

**Comment by MarcusEbert** [comment]
Could you please give me access to csv2-dev & csv2-dev2 to test it?

**Comment by MarcusEbert** [comment]
Looks good on dev2. Will reopen if problems are seen on the production instance later.
