### ISSUE TITLE
bug: different condor instance for a group doesn't work

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#82]
Reproduce:
in the group definition put another host as the Condor Central Manager, e.g. bellecs.heprc.uvic.ca

expected behaviour:
csv2 connects to the distant condor instance to query for jobs

observed behaviour:
nothing happens
There are no entries about "bellecs.heprc.uvic.ca" in any file under /var/log so it seems csv2 doesn't even try to use the distant condor machine.

possible cause:
In "cloudscheduler/data_collectors/condor", condor_host is defined as " condor_host = socket.gethostname()" in 2 places, so it doesn't use the one from the data base.
(In other files, "csgroup.condor_central_manager" is used as cs_condor_host, which is the entry from the database)

**Comment by colsond** [comment]
fixed
