### ISSUE TITLE
Define minimum password requirements.

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#9]
For now the only restriction is that it cannot be blank. I think a minimum and maximum character count should be added.

**Comment by colsond** [comment]
The password functions have been updated to require at least 4 characters with no upper limit.

**Comment by crlb** [comment]
Rules are now:
o can't be ledd the 6 characters.
o less than 16 characters, must have upper, lower and numeric.
o 16 characters or more, can be anything.
