### ISSUE TITLE
Launched VMs do not register with condor by default

### ISSUE THREAD

**Issue by danikam** [hep-gc/cloudscheduler#91]
![csv2_status](https://user-images.githubusercontent.com/43050968/47398557-667d1e80-d6e9-11e8-9c72-4156d77e8197.png)
![csv2_groups](https://user-images.githubusercontent.com/43050968/47398617-ad6b1400-d6e9-11e8-8c2c-446d5f362ed1.png)
![csv2_defaults](https://user-images.githubusercontent.com/43050968/47398618-ad6b1400-d6e9-11e8-9278-271afff1ee2f.png)
![csv2_otter_cloud](https://user-images.githubusercontent.com/43050968/47398620-ad6b1400-d6e9-11e8-9b8e-677f9c9c52b7.png)

After installing csv2 on a new VM (htc-dev) using ansible (see Inventory and ansible-systems), creating a group named 'default' for the default user (csv2_default), and creating a test cloud for otter (see attached screenshots), test jobs submitted with condor_submit successfully launch VMs to run the job (albeit two VMs rather than one, but I think this is a known issue). However, the launched VMs fail to register with condor (see attached screenshot 'csv2_status.png'). For example, running 

~~~~
$ condor_q -better-analyze
~~~~

from the host machine htc-dev.heprc.uvic.ca shows the condor is unaware of the launched VMs:

~~~~
[root@htc-dev condor]# condor_q -better-analyze


-- Schedd: htc-dev.heprc.uvic.ca : <206.12.154.230:48468>
The Requirements expression for job 10.000 is

    ( group_name is "default" && TARGET.Arch == "x86_64" ) && ( TARGET.OpSys == "LINUX" ) && ( TARGET.Disk >= RequestDisk ) && ( TARGET.Memory >= RequestMemory ) && ( TARGET.HasFileTransfer )

Job 10.000 defines the following attributes:

    RequestDisk = 20
    RequestMemory = 5

The Requirements expression for job 10.000 reduces to these conditions:

         Slots
Step    Matched  Condition
-----  --------  ---------
[0]           0  group_name is "default"
[1]           0  TARGET.Arch == "x86_64"
[3]           0  TARGET.OpSys == "LINUX"
[5]           0  TARGET.Disk >= RequestDisk
[7]           0  TARGET.Memory >= RequestMemory
[9]           0  TARGET.HasFileTransfer

No successful match recorded.
Last failed match: Tue Oct 23 17:16:35 2018

Reason for last match failure: no match found 

010.000:  Run analysis summary ignoring user priority.  Of 0 machines,
      0 are rejected by your job's requirements 
      0 reject your job because of their own requirements 
      0 match and are already running your jobs 
      0 match but are serving other users 
      0 are available to run your job

WARNING:  Be advised:
   No machines matched the jobs's constraints
~~~~

Perhaps there is some additional setup required to ensure that the launched VMs will successfully register with condor?

**Comment by rseuster** [comment]
oh, right. You probably miss the default yaml.
on csv2, it is the default.yaml.j2

I put that into my home directory.

You should be able to get this into cloudscheduler by
```
cloudscheduler group metadata-load -f default.yaml.j2 -mn default.yaml.j2 
```
It should work out of the box, more or less.

**Comment by danikam** [comment]
Thank you!! Just tried that out - the new metadata file shows up under Clouds/otter/Metadata (see attached screenshot). Will add this step to ansible. 

After restarting condor and csv2-* and resubmitting the job, condor is now aware of the VMs! :) Now, it's just failing to match job constraints - will debug the constraint issue.
