### ISSUE TITLE
Default csv2 user 'csv2_default' does not have a default group

### ISSUE THREAD

**Issue by danikam** [hep-gc/cloudscheduler#92]
When csv2 is first downloaded with ansible (as was done recently on the htc-dev.heprc.uvic.ca computer), it isn't possible to create a group for the default csv2_default user on the web interface. 

The current workaround is to manually create a group for csv2_default in the mariadb database using the following commands:

~~~~
$ mysql -ucsv2 csv2 -p

$ insert into csv2_groups (group_name, condor_central_manager) values ('default-group', 'htc-dev.heprc.uvic.ca');

$ insert into csv2_user_groups (username, group_name) values ('csv2_default', 'default-group'');
~~~~

However, the Defaults page for this manually created group will be empty, so it's then necessary to create a second group for the csv2_default user using the web interface (I named this new group 'default'), and delete the original default-group group.

**Comment by danikam** [comment]
A workaround (creating the group and adding csv2_default to it with mysql commands) was implemented in ansible. Not sure whether or not there's a need to implement a solution in cloudscheduler as well.

**Comment by colsond** [comment]
fixed
