### ISSUE TITLE
Image and Key cli commands

### ISSUE THREAD

**Issue by colsond** [hep-gc/cloudscheduler#93]
With the glint services now up to speed it makes sense to add the functionality for key and image transfers to the command line.
cmds:
list
upload
transfer
delete?

**Comment by colsond** [comment]
in the works

**Comment by rseuster** [comment]
plan is to re-do a lot of stuff in code. code clean-up.

**Comment by colsond** [comment]
Glint cli support was integrated in the stable-2.7 release.
