### ISSUE TITLE
web interface shows strange results when adding / deleting yaml files

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#98]
problem 1)
when adding a file
on csv2:
go to "Defaults"
go to "Metadata"
add a yaml file by clicking "+"
==> new yaml file doesn't show up in the list in the light yellow box

go to "Status", back to "Defaults" and back to "Metadata", then it shows up.

problem 2)
Now delete the new yaml file.
The error message "Error: group metadata_fetch, file "coca::test.yaml" does not exist." shows up, and a second status bar in the sub frame appears.

**Comment by colsond** [comment]
updates ?

**Comment by kcasteels** [comment]
The  page seems to refresh faster than the database can be updated... Looking into this now.

**Comment by kcasteels** [comment]
This is mostly fixed now. The after metadata add or delete the parent page now refreshes properly and shows the updated metadata list. I now need to get the refreshed page to position at the correct spot.

**Comment by kcasteels** [comment]
I'm going to close this now and add a feature request for page positioning.
