### ISSUE TITLE
web interface: mysql error when changing the group while being in the "Defaults"

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#99]
changing the group while being e.g. in the "Defaults" will produce this error:

Error: GV06-260 group defaults update "coca" failed - (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE csv2_group_defaults.group_name = 'coca'' at line 1") [SQL: 'UPDATE csv2_group_defaults SET WHERE csv2_group_defaults.group_name = %s'] [parameters: ('coca',)] (Background on this error at: http://sqlalche.me/e/f405).

**Comment by colsond** [comment]
updates ?

**Comment by kcasteels** [comment]
This is now fixed.

**Comment by kcasteels** [comment]
Its fixed in the dev branch, on csv2-dev

**Comment by kcasteels** [comment]
This was broken again due to other changes. Fixed once more.

**Comment by rseuster** [comment]
fixed, create new issue if re-occuring
